import type { ChainDrill } from "./types";

// Every drill ends with a song reference — the instant-musicality rule.
// "You cannot play this wrong. Try twice. Move on." or a variant — on every one.

export const CHAIN_DRILLS: ChainDrill[] = [
  // ───── PHASE 1 ─────
  {
    id: "p1-c-major-chain",
    phase: 1,
    name: "C major chain",
    minutes: 4,
    ghostKey: "C",
    pillar: "technique",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "C major, hands separate, 2 octaves, slow." },
      { type: "triad",       durationSec: 15,  instruction: "C major triad, root position, both hands." },
      { type: "progression", durationSec: 45,  instruction: "I–IV–V–I (C–F–G–C), 4 bars. Repeat once." },
      { type: "improv",      durationSec: 120, instruction: "Right hand noodles with C major pentatonic over the loop." },
      { type: "song",        durationSec: 30,  instruction: "First line of Let It Be." },
    ],
    closingNote: "You cannot play this wrong. Try twice. Move on.",
  },
  {
    id: "p1-c-tone-chain",
    phase: 1,
    name: "C tone chain",
    minutes: 4,
    ghostKey: "C",
    pillar: "expression",
    steps: [
      { type: "tone",   durationSec: 45,  instruction: "Weight-transfer 5-finger: C–D–E–F–G–F–E–D–C. Zero tension between strikes." },
      { type: "tone",   durationSec: 45,  instruction: "Same note, five ways: whisper · clear · bright · dark · ringing." },
      { type: "scale",  durationSec: 45,  instruction: "C scale with a dynamic arc — crescendo up, decrescendo down." },
      { type: "song",   durationSec: 45,  instruction: "First bar of River Flows in You — treat each note as a choice." },
      { type: "song",   durationSec: 30,  instruction: "Opening of Moonlight Sonata, whisper-quiet." },
    ],
    closingNote: "Tone is a decision. There is no wrong note tonight.",
  },
  {
    id: "p1-g-major-chain",
    phase: 1,
    name: "G major chain",
    minutes: 4,
    ghostKey: "G",
    pillar: "technique",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "G major, hands separate, 2 octaves. Listen for the F♯." },
      { type: "triad",       durationSec: 15,  instruction: "G major triad. Both hands." },
      { type: "progression", durationSec: 60,  instruction: "G–C–D–G, 4 bars. Repeat with a gentle rhythmic pulse." },
      { type: "improv",      durationSec: 120, instruction: "Right hand, G major pentatonic. Two phrases. End on G." },
      { type: "song",        durationSec: 30,  instruction: "Chorus of Let It Be in G (same progression, different home)." },
    ],
    closingNote: "You cannot play this wrong. Try twice. Move on.",
  },
  {
    id: "p1-f-major-chain",
    phase: 1,
    name: "F major chain",
    minutes: 4,
    ghostKey: "F",
    pillar: "technique",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "F major scale, hands separate. Thumb placement on F and C." },
      { type: "triad",       durationSec: 15,  instruction: "F major triad, root position, both hands." },
      { type: "progression", durationSec: 45,  instruction: "F–Bb–C–F. Feel the Bb as the stretch away from home." },
      { type: "improv",      durationSec: 120, instruction: "Right hand, F major pentatonic. Try landing on A (the 3rd) for warmth." },
      { type: "song",        durationSec: 30,  instruction: "First line of Yesterday (Beatles). It's in F." },
    ],
    closingNote: "Home key. Nothing to prove.",
  },
  {
    id: "p1-a-minor-chain",
    phase: 1,
    name: "A minor longing",
    minutes: 4,
    ghostKey: "am",
    pillar: "ear",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "A natural minor, hands separate, 2 octaves." },
      { type: "triad",       durationSec: 15,  instruction: "A minor triad (A–C–E). Both hands." },
      { type: "progression", durationSec: 60,  instruction: "i–iv–V–i (Am–Dm–E–Am). 4 bars. Feel the E resolve." },
      { type: "improv",      durationSec: 120, instruction: "Right hand, A minor pentatonic. Two phrases. Land somewhere sad." },
      { type: "song",        durationSec: 30,  instruction: "House of the Rising Sun opening." },
    ],
    closingNote: "You cannot play this wrong. Try twice. Move on.",
  },
  {
    id: "p1-d-minor-chain",
    phase: 1,
    name: "D minor dusk",
    minutes: 4,
    ghostKey: "dm",
    pillar: "ear",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "D natural minor scale, hands separate." },
      { type: "triad",       durationSec: 15,  instruction: "D minor triad. Listen to the darkness in the 3rd." },
      { type: "progression", durationSec: 45,  instruction: "i–VI–III–VII (Dm–Bb–F–C). 4 bars." },
      { type: "improv",      durationSec: 120, instruction: "Right hand, D minor pentatonic. Slowly." },
      { type: "song",        durationSec: 30,  instruction: "Mad World intro shape." },
    ],
    closingNote: "It's meant to sit low. Let it.",
  },
  {
    id: "p1-echo-ear",
    phase: 1,
    name: "the echo",
    minutes: 3,
    ghostKey: "C",
    pillar: "ear",
    steps: [
      { type: "transcribe", durationSec: 30, instruction: "Teacher plays 3 notes in C (tap play). You echo." },
      { type: "transcribe", durationSec: 45, instruction: "Teacher plays 4 notes. You echo. Repeat twice." },
      { type: "transcribe", durationSec: 45, instruction: "Now the same but with eyes closed. Find the notes." },
      { type: "improv",     durationSec: 60, instruction: "Your turn — play any 4 notes. Echo your own." },
      { type: "song",       durationSec: 20, instruction: "Happy Birthday, first four notes. You know it." },
    ],
    closingNote: "The ear learned something tonight. It won't forget.",
  },
  {
    id: "p1-three-moods-lite",
    phase: 1,
    name: "three moods, gently",
    minutes: 4,
    ghostKey: "C",
    pillar: "expression",
    steps: [
      { type: "progression", durationSec: 30, instruction: "Set up I–vi–IV–V in C (C–Am–F–G), 4 bars." },
      { type: "moods",       durationSec: 60, instruction: "Play it tender. Soft, close to the keys." },
      { type: "moods",       durationSec: 60, instruction: "Play it restless. A little forward, a little bright." },
      { type: "moods",       durationSec: 60, instruction: "Play it resigned. Slow. Step back at the V." },
      { type: "song",        durationSec: 30, instruction: "Same shape as Let It Be — play its hook once." },
    ],
    closingNote: "Same notes. Different worlds. That was you.",
  },
  {
    id: "p1-canon-chain",
    phase: 1,
    name: "canon chain",
    minutes: 4,
    ghostKey: "C",
    pillar: "repertoire",
    steps: [
      { type: "progression", durationSec: 40, instruction: "Pachelbel's bones: I–V–vi–iii–IV–I–IV–V in C. Play LH slow." },
      { type: "improv",      durationSec: 80, instruction: "Right hand, C major. Land on chord tones on downbeats." },
      { type: "progression", durationSec: 40, instruction: "Again, faster. It's a groove now." },
      { type: "song",        durationSec: 40, instruction: "Canon in D's opening, in C for now. Let it breathe." },
      { type: "song",        durationSec: 30, instruction: "Whatever song you'd play for a friend. No rules." },
    ],
    closingNote: "The oldest progression in the room. Still works.",
  },
  {
    id: "p1-lullaby-chain",
    phase: 1,
    name: "lullaby chain",
    minutes: 4,
    ghostKey: "F",
    pillar: "repertoire",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "F major scale, hands together if you can. 2 octaves, slow." },
      { type: "progression", durationSec: 45,  instruction: "F–Dm–Bb–C. Hold each chord for 4 beats." },
      { type: "improv",      durationSec: 100, instruction: "Right hand — simple notes from F major. Let each one sit." },
      { type: "song",        durationSec: 45,  instruction: "Brahms' Lullaby, opening phrase. In F." },
      { type: "song",        durationSec: 30,  instruction: "Twinkle Twinkle. It's allowed." },
    ],
    closingNote: "Quiet playing is a skill. You practised it.",
  },

  // ───── PHASE 2 ─────
  {
    id: "p2-am-pop-formula",
    phase: 2,
    name: "the pop formula",
    minutes: 5,
    ghostKey: "am",
    pillar: "lead-sheet",
    steps: [
      { type: "progression", durationSec: 45,  instruction: "Am–F–C–G, block chords, LH. 4 bars. Repeat." },
      { type: "improv",      durationSec: 120, instruction: "RH: melody in A minor / C major pentatonic over the loop." },
      { type: "lead-sheet",  durationSec: 60,  instruction: "Same progression — try LH root-5-root-3, RH hums a line." },
      { type: "song",        durationSec: 45,  instruction: "Someone Like You (Adele) — same changes. Play the hook." },
      { type: "song",        durationSec: 45,  instruction: "Let Her Go (Passenger) — same changes, same world." },
    ],
    closingNote: "This progression holds up half the radio. It holds you up too.",
  },
  {
    id: "p2-left-hand-loop",
    phase: 2,
    name: "left-hand loop",
    minutes: 5,
    ghostKey: "am",
    pillar: "technique",
    steps: [
      { type: "progression", durationSec: 30,  instruction: "i–iv–V in A minor, left hand only. Evenly." },
      { type: "improv",      durationSec: 120, instruction: "LH keeps looping. RH plays anything in A minor pentatonic." },
      { type: "improv",      durationSec: 90,  instruction: "Now try 2 phrases: one rising, one falling." },
      { type: "song",        durationSec: 45,  instruction: "Hallelujah verse shape (Cohen) — Am–Dm–Am." },
      { type: "song",        durationSec: 45,  instruction: "Fur Elise opening. A minor. The hand already knows." },
    ],
    closingNote: "Two hands. One of them is already on autopilot. That's independence.",
  },
  {
    id: "p2-song-transcribe",
    phase: 2,
    name: "song transcribe",
    minutes: 5,
    ghostKey: "C",
    pillar: "ear",
    steps: [
      { type: "transcribe", durationSec: 60, instruction: "Play Happy Birthday in C — just the melody, by ear." },
      { type: "transcribe", durationSec: 90, instruction: "Now Ode to Joy. Start on E. Just the first 8 notes." },
      { type: "improv",     durationSec: 90, instruction: "Take those 8 notes. Change one. Play it again." },
      { type: "song",       durationSec: 45, instruction: "Try Twinkle in a different key — G or F." },
      { type: "song",       durationSec: 45, instruction: "Play a hook of a pop song you love. Even badly." },
    ],
    closingNote: "You heard something and put it in your hands. That's the whole game.",
  },
  {
    id: "p2-dm-arpeggio",
    phase: 2,
    name: "D minor arpeggio chain",
    minutes: 5,
    ghostKey: "dm",
    pillar: "technique",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "D minor scale, hands together, 2 octaves, 80bpm." },
      { type: "parallel-set",durationSec: 60, instruction: "D minor arpeggio (D–F–A–D), fast bursts of 4 notes. Pauses between." },
      { type: "progression", durationSec: 45, instruction: "i–iv–V in D minor. LH arpeggiated pattern." },
      { type: "improv",      durationSec: 90, instruction: "RH improv with D minor pentatonic over the arpeggios." },
      { type: "song",        durationSec: 45, instruction: "Comptine d'un autre été — Amélie theme. D minor territory." },
    ],
    closingNote: "Arpeggios are chords on stairs. Now you can walk up and down them.",
  },
  {
    id: "p2-e-minor-mood",
    phase: 2,
    name: "E minor mood",
    minutes: 5,
    ghostKey: "em",
    pillar: "expression",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "E natural minor scale, hands together." },
      { type: "progression", durationSec: 45, instruction: "i–III–VII–VI in Em (Em–G–D–C). 4 bars." },
      { type: "moods",       durationSec: 60, instruction: "Play it mournful. Pedal heavy. Slow." },
      { type: "moods",       durationSec: 60, instruction: "Now play it quietly hopeful. Lighter touch. Same chords." },
      { type: "song",        durationSec: 60, instruction: "Interstellar main theme — that kind of ache." },
    ],
    closingNote: "Same notes, different human. That was your hand.",
  },
  {
    id: "p2-g-lead-sheet",
    phase: 2,
    name: "lead sheet start",
    minutes: 5,
    ghostKey: "G",
    pillar: "lead-sheet",
    steps: [
      { type: "lead-sheet",  durationSec: 45, instruction: "G–Em–C–D — LH plays block chords, RH rests." },
      { type: "lead-sheet",  durationSec: 60, instruction: "Now RH picks out the melody of a song you know — LH keeps comping." },
      { type: "progression", durationSec: 45, instruction: "Same changes, LH broken-chord 'waltz' pattern." },
      { type: "improv",      durationSec: 60, instruction: "Over G–Em–C–D — RH improvises 8 bars in G major." },
      { type: "song",        durationSec: 30, instruction: "Take Me Home, Country Roads — exact same changes." },
    ],
    closingNote: "You're reading chord symbols while playing. That's a professional skill.",
  },
  {
    id: "p2-bb-dreamscape",
    phase: 2,
    name: "Bb dreamscape",
    minutes: 5,
    ghostKey: "Bb",
    pillar: "technique",
    steps: [
      { type: "scale",       durationSec: 45, instruction: "Bb major scale, hands separate. Thumb on F." },
      { type: "triad",       durationSec: 30, instruction: "Bb and its IV (Eb). Practise the shift." },
      { type: "progression", durationSec: 45, instruction: "Bb–Eb–F–Bb. Hold each chord softly." },
      { type: "improv",      durationSec: 90, instruction: "Right hand noodles with Bb pentatonic. Sustain pedal gentle." },
      { type: "song",        durationSec: 30, instruction: "Imagine (Lennon) is in F, but open it from Bb — feel the closeness." },
    ],
    closingNote: "Flat keys feel softer. That's not imagined.",
  },
  {
    id: "p2-d-major-daylight",
    phase: 2,
    name: "D major daylight",
    minutes: 5,
    ghostKey: "D",
    pillar: "repertoire",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "D major scale, hands together if you can. Two sharps." },
      { type: "progression", durationSec: 45, instruction: "I–V–vi–IV (D–A–Bm–G). Classic pop in D." },
      { type: "improv",      durationSec: 90, instruction: "D major pentatonic, right hand. Aim for an 8-bar melody." },
      { type: "song",        durationSec: 45, instruction: "Canon in D — its own changes. Just the first 8 bars." },
      { type: "song",        durationSec: 30, instruction: "Hey Jude verse — same four chords." },
    ],
    closingNote: "Bright key. Bright day. Well done.",
  },
  {
    id: "p2-three-moods",
    phase: 2,
    name: "three moods",
    minutes: 5,
    ghostKey: "C",
    pillar: "expression",
    steps: [
      { type: "progression", durationSec: 30, instruction: "vi–IV–I–V in C (Am–F–C–G). 4 bars." },
      { type: "moods",       durationSec: 60, instruction: "Tender. Touch the keys. Nothing loud." },
      { type: "moods",       durationSec: 60, instruction: "Angry. Weight, not volume. Crisp release." },
      { type: "moods",       durationSec: 60, instruction: "Resigned. Slower. Land heavy on V." },
      { type: "song",        durationSec: 60, instruction: "Someone Like You — same four chords. Play it one of your three ways." },
    ],
    closingNote: "The notes didn't change. You did.",
  },

  // ───── PHASE 3 ─────
  {
    id: "p3-pop-pull",
    phase: 3,
    name: "pop pull",
    minutes: 6,
    ghostKey: "C",
    pillar: "ear",
    steps: [
      { type: "transcribe",  durationSec: 90,  instruction: "Pick a pop hook you half-know. Find it on the piano, 4 bars." },
      { type: "transcribe",  durationSec: 90,  instruction: "Now find a plausible chord under each bar. Root notes only." },
      { type: "improv",      durationSec: 90,  instruction: "Play the melody + chords together. Mess it up, fix it, repeat." },
      { type: "song",        durationSec: 60,  instruction: "Same hook, up a whole tone. Harder. Do it anyway." },
      { type: "song",        durationSec: 30,  instruction: "End with a song that makes you smile." },
    ],
    closingNote: "You pulled a song out of the air into your hands. That's the goal of the whole app.",
  },
  {
    id: "p3-ii-v-i-taste",
    phase: 3,
    name: "ii–V–I, first taste",
    minutes: 6,
    ghostKey: "F",
    pillar: "lead-sheet",
    steps: [
      { type: "progression", durationSec: 45, instruction: "ii–V–I in F (Gm–C7–F). LH shell voicings: root, 3rd, 7th." },
      { type: "improv",      durationSec: 120,instruction: "RH: F major scale, land on chord tones on the downbeats." },
      { type: "progression", durationSec: 45, instruction: "ii–V–I in C (Dm–G7–C). Same pattern, new key." },
      { type: "song",        durationSec: 60, instruction: "Autumn Leaves — opens with exactly ii–V–I. Play the hook." },
      { type: "song",        durationSec: 30, instruction: "Something of your own invention. 8 bars. You know enough now." },
    ],
    closingNote: "You just touched jazz. It didn't bite.",
  },
  {
    id: "p3-substitution-blues",
    phase: 3,
    name: "substitution blues",
    minutes: 6,
    ghostKey: "G",
    pillar: "lead-sheet",
    steps: [
      { type: "progression", durationSec: 60, instruction: "I–vi–ii–V in G (G–Em–Am–D). 8 bars." },
      { type: "progression", durationSec: 60, instruction: "Now swap vi for iii (Bm). Same 8 bars. Feel the colour change." },
      { type: "progression", durationSec: 60, instruction: "Add 7ths: Gmaj7–Em7–Am7–D7. Smoother." },
      { type: "improv",      durationSec: 90, instruction: "Improvise over version 3 using G major scale." },
      { type: "song",        durationSec: 30, instruction: "Fly Me to the Moon — sits in this neighbourhood." },
    ],
    closingNote: "Same chords. Different colour every time. That's arrangement.",
  },
  {
    id: "p3-eb-ballad",
    phase: 3,
    name: "Eb ballad",
    minutes: 6,
    ghostKey: "Eb",
    pillar: "repertoire",
    steps: [
      { type: "scale",       durationSec: 45, instruction: "Eb major scale, hands together. Three flats." },
      { type: "progression", durationSec: 60, instruction: "I–V–vi–IV in Eb (Eb–Bb–Cm–Ab). Slow, pedalled." },
      { type: "improv",      durationSec: 90, instruction: "Right hand, Eb major scale. Stretch phrases to 4 bars each." },
      { type: "song",        durationSec: 60, instruction: "Somewhere Over the Rainbow — Eb is its native home." },
      { type: "song",        durationSec: 45, instruction: "End with something slow. Make it breathe." },
    ],
    closingNote: "Ballads are where your voice shows up. That was yours.",
  },
  {
    id: "p3-a-jazz",
    phase: 3,
    name: "A minor 7th colour",
    minutes: 6,
    ghostKey: "am",
    pillar: "lead-sheet",
    steps: [
      { type: "progression", durationSec: 45, instruction: "i7–iv7–V7–i7 in A minor (Am7–Dm7–E7–Am7)." },
      { type: "lead-sheet",  durationSec: 60, instruction: "LH: shell voicings (root + 3rd + 7th). RH: rest on beats 1 and 3." },
      { type: "improv",      durationSec: 90, instruction: "RH: A minor scale, landing on chord tones." },
      { type: "song",        durationSec: 60, instruction: "Summertime (Gershwin) — this neighbourhood exactly." },
      { type: "song",        durationSec: 45, instruction: "One chorus of Autumn Leaves, your way." },
    ],
    closingNote: "7ths are the colour of grown-up harmony. You earned them.",
  },
  {
    id: "p3-blues-starter",
    phase: 3,
    name: "12-bar blues starter",
    minutes: 6,
    ghostKey: "C",
    pillar: "improv" as const as ChainDrill["pillar"],
    steps: [
      { type: "progression", durationSec: 60, instruction: "12-bar blues in C: C7 (4 bars) F7 (2) C7 (2) G7 (1) F7 (1) C7 (2)." },
      { type: "progression", durationSec: 60, instruction: "LH: roots only. Feel the 12-bar frame." },
      { type: "improv",      durationSec: 90, instruction: "RH: C minor pentatonic + blue note. Anywhere. Swing eighths." },
      { type: "improv",      durationSec: 60, instruction: "Call and response: LH plays a fill, then RH answers." },
      { type: "song",        durationSec: 30, instruction: "Play any blues lick you've heard. Even one bar. It'll sound right." },
    ],
    closingNote: "You just played blues. You didn't need permission.",
  },
  {
    id: "p3-modulation-test",
    phase: 3,
    name: "modulation walk",
    minutes: 6,
    ghostKey: "C",
    pillar: "ear",
    steps: [
      { type: "progression", durationSec: 60, instruction: "Play I–V–vi–IV in C (C–G–Am–F). Once. Cleanly." },
      { type: "progression", durationSec: 60, instruction: "Now do it in G. Then D. Then A. 4 bars each. 1 min total." },
      { type: "improv",      durationSec: 60, instruction: "Improvise 8 bars in whichever key felt best." },
      { type: "song",        durationSec: 60, instruction: "Hey Jude ends modulating. Play that ending. It's a lift." },
      { type: "song",        durationSec: 30, instruction: "Choose a song. Play it up a half step for 4 bars. Weird is OK." },
    ],
    closingNote: "Keys aren't rooms. They're open fields. You walked between them.",
  },
  {
    id: "p3-voice-leading",
    phase: 3,
    name: "voice leading",
    minutes: 6,
    ghostKey: "F",
    pillar: "expression",
    steps: [
      { type: "progression", durationSec: 60, instruction: "F–Dm–Bb–C. Block chords, root position." },
      { type: "progression", durationSec: 60, instruction: "Now move the top note smoothly across the changes. Minimum movement." },
      { type: "improv",      durationSec: 90, instruction: "RH: lean into the top note as if it's the melody. Make it sing." },
      { type: "song",        durationSec: 60, instruction: "Hikaru Nara (Your Lie in April OP) — voice-leading heaven." },
      { type: "song",        durationSec: 30, instruction: "Play anything — but make the top note the story." },
    ],
    closingNote: "The top voice is the lyric, even without words.",
  },
  {
    id: "p3-pentatonic-fluent",
    phase: 3,
    name: "pentatonic, fluent",
    minutes: 6,
    ghostKey: "em",
    pillar: "improv" as ChainDrill["pillar"],
    steps: [
      { type: "scale",       durationSec: 30, instruction: "E minor pentatonic, hands separate, 2 octaves." },
      { type: "progression", durationSec: 45, instruction: "i–III–VII–VI in Em (Em–G–D–C). LH only." },
      { type: "improv",      durationSec: 120,instruction: "RH: E minor pentatonic. Short phrases first. Then stretch to 4 bars." },
      { type: "improv",      durationSec: 60, instruction: "Add rest — silence is notes too. One bar of music, one bar of nothing." },
      { type: "song",        durationSec: 45, instruction: "La La Land — Mia and Sebastian's theme. E minor cousin." },
    ],
    closingNote: "Improvising with rest is the pro move. You're doing it.",
  },
  {
    id: "p3-sight-read-light",
    phase: 3,
    name: "sight read, light",
    minutes: 5,
    ghostKey: "G",
    pillar: "repertoire",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "G major scale, hands together." },
      { type: "progression", durationSec: 45, instruction: "G–D–Em–C. Block chords LH. Simple." },
      { type: "improv",      durationSec: 60, instruction: "Open a lead sheet from your free-slot URL. Read 4 bars. Be rough." },
      { type: "improv",      durationSec: 60, instruction: "Same 4 bars again. Better this time." },
      { type: "song",        durationSec: 60, instruction: "End on a piece you love, memorised. Anything." },
    ],
    closingNote: "Reading well is reading twice. You did.",
  },
];

export function findDrill(id: string) {
  return CHAIN_DRILLS.find((d) => d.id === id);
}
