import type { ChainDrill } from "../types";
import { withDefaultMotorConfigAll } from "../drillConfig";

// V4 soul-first: `soulName` adds a feel-first heading per drill (e.g. "The Home
// Shape" for the C major chain), matching the node soulTitles in skillNodes.ts.
// The theory `name` stays as the fallback when soulName is absent.
//
// Every drill ends with a song reference — the instant-musicality rule.
// "You cannot play this wrong. Try twice. Move on." or a variant — on every one.

// Raw authored drills. The 3 Phase-1 technique drills declare their own
// repBlocks + bpmLadder; the rest are augmented below so they stop running flat
// (#2): every drill gets a micro-rest cadence, and tempo-relevant drills get a
// default tempo ladder. Pure-expression/mood and by-ear drills get the cadence
// but no ladder (see drillConfig.drillWantsTempoLadder).
const RAW_CHAIN_DRILLS: ChainDrill[] = [
  // ───── PHASE 1 ─────
  {
    id: "p1-c-major-chain",
    instrument: "piano",
    phase: 1,
    name: "C major chain",
    soulName: "The Home Shape",
    minutes: 4,
    ghostKey: "C",
    pillar: "technique",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "C major, hands separate, 2 octaves, slow." },
      { type: "triad",       durationSec: 15,  instruction: "C major triad, root position, both hands." },
      { type: "progression", durationSec: 45,  instruction: "I–IV–V–I (C–F–G–C), 4 bars. Repeat once." },
      { type: "improv",      durationSec: 120, instruction: "Right hand noodles with C major pentatonic over the loop." },
      { type: "song",        durationSec: 30,  instruction: "First line of Let It Be." },
    ],
    closingNote: "You cannot play this wrong. Try twice. Move on.",
    // V3 seed: micro-rest cadence + tempo ladder; eligible for interleaving.
    repBlocks: { repsPerBlock: 3, restSec: 12 },
    bpmLadder: { startBpm: 60, targetBpm: 100, step: 5, advanceAfterSuccesses: 3 },
    interleavable: true,
  },
  {
    // B1 fix — First Improvisation is reachable with only C major learned, so it
    // must stay inside C. A one-chord C vamp (held C chord + C pentatonic noodle)
    // needs no F/G/Am the learner has not been taught yet. Pure expression: no
    // tempo ladder (a metronome target on "make it up" is musically wrong).
    id: "p1-first-improv",
    instrument: "piano",
    phase: 1,
    name: "first improv, one chord",
    soulName: "Make It Up",
    minutes: 4,
    ghostKey: "C",
    pillar: "expression",
    steps: [
      { type: "tone",   durationSec: 30,  instruction: "Left hand: hold a C major chord (C, E, G) and let it ring. That is your whole backing tonight." },
      { type: "improv", durationSec: 120, instruction: "Right hand: play C, D, E, G, A (the C pentatonic) in any order, slowly. Every one of these five fits over the held C." },
      { type: "improv", durationSec: 60,  instruction: "Now use space. Hold some notes long, leave gaps of silence, repeat a little 3-note idea." },
      { type: "improv", durationSec: 30,  instruction: "Land on C whenever you want the phrase to feel home. That is how a musical sentence ends." },
      { type: "song",   durationSec: 30,  instruction: "Someone Like You (Adele) floats a melody over held chords, exactly what you just did." },
    ],
    closingNote: "You made something up and it sounded good. That was you.",
  },
  {
    id: "p1-c-tone-chain",
    instrument: "piano",
    phase: 1,
    name: "C tone chain",
    soulName: "Every Note a Choice",
    minutes: 4,
    ghostKey: "C",
    pillar: "expression",
    steps: [
      { type: "tone",   durationSec: 45,  instruction: "Weight-transfer 5-finger: C–D–E–F–G–F–E–D–C. Zero tension between strikes." },
      { type: "tone",   durationSec: 45,  instruction: "Same note, five ways: whisper · clear · bright · dark · ringing." },
      { type: "scale",  durationSec: 45,  instruction: "C scale with a dynamic arc — crescendo up, decrescendo down." },
      { type: "song",   durationSec: 45,  instruction: "First bar of River Flows in You — treat each note as a choice." },
      { type: "song",   durationSec: 30,  instruction: "Opening of Moonlight Sonata, whisper-quiet." },
    ],
    closingNote: "Tone is a decision. There is no wrong note tonight.",
  },
  {
    id: "p1-g-major-chain",
    instrument: "piano",
    phase: 1,
    name: "G major chain",
    soulName: "One Sharp",
    minutes: 4,
    ghostKey: "G",
    pillar: "technique",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "G major, hands separate, 2 octaves. Listen for the F♯." },
      { type: "triad",       durationSec: 15,  instruction: "G major triad. Both hands." },
      { type: "progression", durationSec: 60,  instruction: "G–C–D–G, 4 bars. Repeat with a gentle rhythmic pulse." },
      { type: "improv",      durationSec: 120, instruction: "Right hand, G major pentatonic. Two phrases. End on G." },
      { type: "song",        durationSec: 30,  instruction: "Chorus of Let It Be in G (same progression, different home)." },
    ],
    closingNote: "You cannot play this wrong. Try twice. Move on.",
    // V3 seed: micro-rest cadence + tempo ladder; eligible for interleaving.
    repBlocks: { repsPerBlock: 3, restSec: 12 },
    bpmLadder: { startBpm: 60, targetBpm: 100, step: 5, advanceAfterSuccesses: 3 },
    interleavable: true,
  },
  {
    id: "p1-f-major-chain",
    instrument: "piano",
    phase: 1,
    name: "F major chain",
    soulName: "One Flat",
    minutes: 4,
    ghostKey: "F",
    pillar: "technique",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "F major scale, hands separate. Thumb placement on F and C." },
      { type: "triad",       durationSec: 15,  instruction: "F major triad, root position, both hands." },
      { type: "progression", durationSec: 45,  instruction: "F–Bb–C–F. Feel the Bb as the stretch away from home." },
      { type: "improv",      durationSec: 120, instruction: "Right hand, F major pentatonic. Try landing on A (the 3rd) for warmth." },
      { type: "song",        durationSec: 30,  instruction: "First line of Yesterday (Beatles). It's in F." },
    ],
    closingNote: "Home key. Nothing to prove.",
    // V3 seed: micro-rest cadence + tempo ladder; eligible for interleaving.
    repBlocks: { repsPerBlock: 3, restSec: 12 },
    bpmLadder: { startBpm: 60, targetBpm: 100, step: 5, advanceAfterSuccesses: 3 },
    interleavable: true,
  },
  {
    id: "p1-a-minor-chain",
    instrument: "piano",
    phase: 1,
    name: "A minor longing",
    soulName: "The Sad Shape",
    minutes: 4,
    ghostKey: "am",
    pillar: "ear",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "A natural minor, hands separate, 2 octaves." },
      { type: "triad",       durationSec: 15,  instruction: "A minor triad (A–C–E). Both hands." },
      { type: "progression", durationSec: 60,  instruction: "i–iv–V–i (Am–Dm–E–Am). 4 bars. Feel the E resolve." },
      { type: "improv",      durationSec: 120, instruction: "Right hand, A minor pentatonic. Two phrases. Land somewhere sad." },
      { type: "song",        durationSec: 30,  instruction: "House of the Rising Sun opening." },
    ],
    closingNote: "You cannot play this wrong. Try twice. Move on.",
  },
  {
    id: "p1-d-minor-chain",
    instrument: "piano",
    phase: 1,
    name: "D minor dusk",
    soulName: "Sit Low and Stay",
    minutes: 4,
    ghostKey: "dm",
    pillar: "ear",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "D natural minor scale, hands separate." },
      { type: "triad",       durationSec: 15,  instruction: "D minor triad. Listen to the darkness in the 3rd." },
      { type: "progression", durationSec: 45,  instruction: "i–VI–III–VII (Dm–Bb–F–C). 4 bars." },
      { type: "improv",      durationSec: 120, instruction: "Right hand, D minor pentatonic. Slowly." },
      { type: "song",        durationSec: 30,  instruction: "Mad World intro shape." },
    ],
    closingNote: "It's meant to sit low. Let it.",
  },
  {
    id: "p1-echo-ear",
    instrument: "piano",
    phase: 1,
    name: "the echo",
    soulName: "Echo It Back",
    minutes: 3,
    ghostKey: "C",
    pillar: "ear",
    steps: [
      { type: "transcribe", durationSec: 30, instruction: "Teacher plays 3 notes in C (tap play). You echo." },
      { type: "transcribe", durationSec: 45, instruction: "Teacher plays 4 notes. You echo. Repeat twice." },
      { type: "transcribe", durationSec: 45, instruction: "Now the same but with eyes closed. Find the notes." },
      { type: "improv",     durationSec: 60, instruction: "Your turn — play any 4 notes. Echo your own." },
      { type: "song",       durationSec: 20, instruction: "Happy Birthday, first four notes. You know it." },
    ],
    closingNote: "The ear learned something tonight. It won't forget.",
  },
  {
    // B1 fix — Three Moods is reachable with only C major learned, so the material
    // stays inside C: a simple C-major line (C D E F G) played three ways. No Am/F/G
    // chords the learner has not met yet. Pure expression, so no tempo ladder.
    id: "p1-three-moods-lite",
    instrument: "piano",
    phase: 1,
    name: "three moods, gently",
    soulName: "Same Notes, Three Feelings",
    minutes: 4,
    ghostKey: "C",
    pillar: "expression",
    steps: [
      { type: "tone",  durationSec: 30, instruction: "Set a simple line in C: play C D E F G, then back down. One hand, all white keys." },
      { type: "moods", durationSec: 60, instruction: "Play it tender. Soft and slow, let each note ring into the next." },
      { type: "moods", durationSec: 60, instruction: "Play it restless. A little faster, a little brighter, pushing forward." },
      { type: "moods", durationSec: 60, instruction: "Play it resigned. Slow and heavy. Leave gaps and let it sag." },
      { type: "song",  durationSec: 30, instruction: "Ode to Joy opens with just these notes. Play its first line your favourite of the three ways." },
    ],
    closingNote: "Same notes. Different worlds. That was you.",
  },
  {
    id: "p1-canon-chain",
    instrument: "piano",
    phase: 1,
    name: "canon chain",
    soulName: "The Oldest Groove",
    minutes: 4,
    ghostKey: "C",
    pillar: "repertoire",
    steps: [
      { type: "progression", durationSec: 40, instruction: "Pachelbel's bones: I–V–vi–iii–IV–I–IV–V in C. Play LH slow." },
      { type: "improv",      durationSec: 80, instruction: "Right hand, C major. Land on chord tones on downbeats." },
      { type: "progression", durationSec: 40, instruction: "Again, faster. It's a groove now." },
      { type: "song",        durationSec: 40, instruction: "Canon in D's opening, in C for now. Let it breathe." },
      { type: "song",        durationSec: 30, instruction: "Whatever song you'd play for a friend. No rules." },
    ],
    closingNote: "The oldest progression in the room. Still works.",
  },
  {
    id: "p1-lullaby-chain",
    instrument: "piano",
    phase: 1,
    name: "lullaby chain",
    soulName: "Play It Quiet",
    minutes: 4,
    ghostKey: "F",
    pillar: "repertoire",
    steps: [
      { type: "scale",       durationSec: 30,  instruction: "F major scale, hands together if you can. 2 octaves, slow." },
      { type: "progression", durationSec: 45,  instruction: "F–Dm–Bb–C. Hold each chord for 4 beats." },
      { type: "improv",      durationSec: 100, instruction: "Right hand — simple notes from F major. Let each one sit." },
      { type: "song",        durationSec: 45,  instruction: "Brahms' Lullaby, opening phrase. In F." },
      { type: "song",        durationSec: 30,  instruction: "Twinkle Twinkle. It's allowed." },
    ],
    closingNote: "Quiet playing is a skill. You practised it.",
  },

  // ───── PHASE 2 ─────
  {
    id: "p2-am-pop-formula",
    instrument: "piano",
    phase: 2,
    name: "the pop formula",
    soulName: "Half of All Pop",
    minutes: 5,
    ghostKey: "am",
    pillar: "lead-sheet",
    steps: [
      { type: "progression", durationSec: 45,  instruction: "Am–F–C–G, block chords, LH. 4 bars. Repeat." },
      { type: "improv",      durationSec: 120, instruction: "RH: melody in A minor / C major pentatonic over the loop." },
      { type: "lead-sheet",  durationSec: 60,  instruction: "Same progression — try LH root-5-root-3, RH hums a line." },
      { type: "song",        durationSec: 45,  instruction: "Someone Like You (Adele) — same changes. Play the hook." },
      { type: "song",        durationSec: 45,  instruction: "Let Her Go (Passenger) — same changes, same world." },
    ],
    closingNote: "This progression holds up half the radio. It holds you up too.",
  },
  {
    id: "p2-left-hand-loop",
    instrument: "piano",
    phase: 2,
    name: "left-hand loop",
    soulName: "Improvise Without Panic",
    minutes: 5,
    ghostKey: "am",
    pillar: "technique",
    steps: [
      { type: "progression", durationSec: 30,  instruction: "i–iv–V in A minor, left hand only. Evenly." },
      { type: "improv",      durationSec: 120, instruction: "LH keeps looping. RH plays anything in A minor pentatonic." },
      { type: "improv",      durationSec: 90,  instruction: "Now try 2 phrases: one rising, one falling." },
      { type: "song",        durationSec: 45,  instruction: "Hallelujah verse shape (Cohen) — Am–Dm–Am." },
      { type: "song",        durationSec: 45,  instruction: "Fur Elise opening. A minor. The hand already knows." },
    ],
    closingNote: "Two hands. One of them is already on autopilot. That's independence.",
  },
  {
    id: "p2-song-transcribe",
    instrument: "piano",
    phase: 2,
    name: "song transcribe",
    soulName: "Play It By Ear",
    minutes: 5,
    ghostKey: "C",
    pillar: "ear",
    steps: [
      { type: "transcribe", durationSec: 60, instruction: "Play Happy Birthday in C — just the melody, by ear." },
      { type: "transcribe", durationSec: 90, instruction: "Now Ode to Joy. Start on E. Just the first 8 notes." },
      { type: "improv",     durationSec: 90, instruction: "Take those 8 notes. Change one. Play it again." },
      { type: "song",       durationSec: 45, instruction: "Try Twinkle in a different key — G or F." },
      { type: "song",       durationSec: 45, instruction: "Play a hook of a pop song you love. Even badly." },
    ],
    closingNote: "You heard something and put it in your hands. That's the whole game.",
  },
  {
    id: "p2-dm-arpeggio",
    instrument: "piano",
    phase: 2,
    name: "D minor arpeggio chain",
    soulName: "Chords on Stairs",
    minutes: 5,
    ghostKey: "dm",
    pillar: "technique",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "D minor scale, hands together, 2 octaves, 80bpm." },
      { type: "parallel-set",durationSec: 60, instruction: "D minor arpeggio (D–F–A–D), fast bursts of 4 notes. Pauses between." },
      { type: "progression", durationSec: 45, instruction: "i–iv–V in D minor. LH arpeggiated pattern." },
      { type: "improv",      durationSec: 90, instruction: "RH improv with D minor pentatonic over the arpeggios." },
      { type: "song",        durationSec: 45, instruction: "Comptine d'un autre été — Amélie theme. D minor territory." },
    ],
    closingNote: "Arpeggios are chords on stairs. Now you can walk up and down them.",
  },
  {
    id: "p2-e-minor-mood",
    instrument: "piano",
    phase: 2,
    name: "E minor mood",
    soulName: "Dark and Cinematic",
    minutes: 5,
    ghostKey: "em",
    pillar: "expression",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "E natural minor scale, hands together." },
      { type: "progression", durationSec: 45, instruction: "i–III–VII–VI in Em (Em–G–D–C). 4 bars." },
      { type: "moods",       durationSec: 60, instruction: "Play it mournful and slow. If you have learned the sustain pedal, lean on it here; if not, let your fingers hold each note so they overlap gently." },
      { type: "moods",       durationSec: 60, instruction: "Now play it quietly hopeful. Lighter touch. Same chords." },
      { type: "song",        durationSec: 60, instruction: "Interstellar main theme — that kind of ache." },
    ],
    closingNote: "Same notes, different human. That was your hand.",
  },
  {
    id: "p2-g-lead-sheet",
    instrument: "piano",
    phase: 2,
    name: "lead sheet start",
    soulName: "Read and Play at Once",
    minutes: 5,
    ghostKey: "G",
    pillar: "lead-sheet",
    steps: [
      { type: "lead-sheet",  durationSec: 45, instruction: "G–Em–C–D — LH plays block chords, RH rests." },
      { type: "lead-sheet",  durationSec: 60, instruction: "Now RH picks out the melody of a song you know — LH keeps comping." },
      { type: "progression", durationSec: 45, instruction: "Same changes, LH broken-chord 'waltz' pattern." },
      { type: "improv",      durationSec: 60, instruction: "Over G–Em–C–D — RH improvises 8 bars in G major." },
      { type: "song",        durationSec: 30, instruction: "Take Me Home, Country Roads — exact same changes." },
    ],
    closingNote: "You're reading chord symbols while playing. That's a professional skill.",
  },
  {
    id: "p2-bb-dreamscape",
    instrument: "piano",
    phase: 2,
    name: "Bb dreamscape",
    soulName: "The Soft Key",
    minutes: 5,
    ghostKey: "Bb",
    pillar: "technique",
    steps: [
      { type: "scale",       durationSec: 45, instruction: "Bb major scale, hands separate. Thumb on F." },
      { type: "triad",       durationSec: 30, instruction: "Bb and its IV (Eb). Practise the shift." },
      { type: "progression", durationSec: 45, instruction: "Bb–Eb–F–Bb. Hold each chord softly." },
      { type: "improv",      durationSec: 90, instruction: "Right hand noodles with Bb pentatonic. If you have the sustain pedal, use it gently; otherwise let the notes ring into each other under your fingers." },
      { type: "song",        durationSec: 30, instruction: "Imagine (Lennon) is in F, but open it from Bb — feel the closeness." },
    ],
    closingNote: "Flat keys feel softer. That's not imagined.",
  },
  {
    id: "p2-d-major-daylight",
    instrument: "piano",
    phase: 2,
    name: "D major daylight",
    soulName: "Bright and Wide Open",
    minutes: 5,
    ghostKey: "D",
    pillar: "repertoire",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "D major scale, hands together if you can. Two sharps." },
      { type: "progression", durationSec: 45, instruction: "I–V–vi–IV (D–A–Bm–G). Classic pop in D." },
      { type: "improv",      durationSec: 90, instruction: "D major pentatonic, right hand. Aim for an 8-bar melody." },
      { type: "song",        durationSec: 45, instruction: "Canon in D — its own changes. Just the first 8 bars." },
      { type: "song",        durationSec: 30, instruction: "Hey Jude verse — same four chords." },
    ],
    closingNote: "Bright key. Bright day. Well done.",
  },
  {
    id: "p2-three-moods",
    instrument: "piano",
    phase: 2,
    name: "three moods",
    soulName: "Feel, Not Notes",
    minutes: 5,
    ghostKey: "C",
    pillar: "expression",
    steps: [
      { type: "progression", durationSec: 30, instruction: "vi–IV–I–V in C (Am–F–C–G). 4 bars." },
      { type: "moods",       durationSec: 60, instruction: "Tender. Touch the keys. Nothing loud." },
      { type: "moods",       durationSec: 60, instruction: "Angry. Weight, not volume. Crisp release." },
      { type: "moods",       durationSec: 60, instruction: "Resigned. Slower. Land heavy on V." },
      { type: "song",        durationSec: 60, instruction: "Someone Like You — same four chords. Play it one of your three ways." },
    ],
    closingNote: "The notes didn't change. You did.",
  },

  // ───── PHASE 3 ─────
  {
    id: "p3-pop-pull",
    instrument: "piano",
    phase: 3,
    name: "pop pull",
    soulName: "Pull a Song Off a Record",
    minutes: 6,
    ghostKey: "C",
    pillar: "ear",
    steps: [
      { type: "transcribe",  durationSec: 90,  instruction: "Pick a pop hook you half-know. Find it on the piano, 4 bars." },
      { type: "transcribe",  durationSec: 90,  instruction: "Now find a plausible chord under each bar. Root notes only." },
      { type: "improv",      durationSec: 90,  instruction: "Play the melody + chords together. Mess it up, fix it, repeat." },
      { type: "song",        durationSec: 60,  instruction: "Same hook, up a whole tone. Harder. Do it anyway." },
      { type: "song",        durationSec: 30,  instruction: "End with a song that makes you smile." },
    ],
    closingNote: "You pulled a song out of the air into your hands. That's the goal of the whole app.",
  },
  {
    id: "p3-ii-v-i-taste",
    instrument: "piano",
    phase: 3,
    name: "ii–V–I, first taste",
    soulName: "Touch Jazz",
    minutes: 6,
    ghostKey: "F",
    pillar: "lead-sheet",
    steps: [
      { type: "progression", durationSec: 45, instruction: "ii–V–I in F (Gm–C7–F). LH shell voicings: root, 3rd, 7th." },
      { type: "improv",      durationSec: 120,instruction: "RH: F major scale, land on chord tones on the downbeats." },
      { type: "progression", durationSec: 45, instruction: "ii–V–I in C (Dm–G7–C). Same pattern, new key." },
      { type: "song",        durationSec: 60, instruction: "Autumn Leaves — opens with exactly ii–V–I. Play the hook." },
      { type: "song",        durationSec: 30, instruction: "Something of your own invention. 8 bars. You know enough now." },
    ],
    closingNote: "You just touched jazz. It didn't bite.",
  },
  {
    id: "p3-substitution-blues",
    instrument: "piano",
    phase: 3,
    name: "substitution blues",
    soulName: "Same Chords, New Colour",
    minutes: 6,
    ghostKey: "G",
    pillar: "lead-sheet",
    steps: [
      { type: "progression", durationSec: 60, instruction: "I–vi–ii–V in G (G–Em–Am–D). 8 bars." },
      { type: "progression", durationSec: 60, instruction: "Now swap vi for iii (Bm). Same 8 bars. Feel the colour change." },
      { type: "progression", durationSec: 60, instruction: "Add 7ths: Gmaj7–Em7–Am7–D7. Smoother." },
      { type: "improv",      durationSec: 90, instruction: "Improvise over version 3 using G major scale." },
      { type: "song",        durationSec: 30, instruction: "Fly Me to the Moon — sits in this neighbourhood." },
    ],
    closingNote: "Same chords. Different colour every time. That's arrangement.",
  },
  {
    id: "p3-eb-ballad",
    instrument: "piano",
    phase: 3,
    name: "Eb ballad",
    soulName: "Where Your Voice Shows Up",
    minutes: 6,
    ghostKey: "Eb",
    pillar: "repertoire",
    steps: [
      { type: "scale",       durationSec: 45, instruction: "Eb major scale, hands together. Three flats." },
      { type: "progression", durationSec: 60, instruction: "I–V–vi–IV in Eb (Eb–Bb–Cm–Ab). Slow. Pedal it if you have learned the sustain pedal; otherwise hold each chord full length so it flows." },
      { type: "improv",      durationSec: 90, instruction: "Right hand, Eb major scale. Stretch phrases to 4 bars each." },
      { type: "song",        durationSec: 60, instruction: "Somewhere Over the Rainbow — Eb is its native home." },
      { type: "song",        durationSec: 45, instruction: "End with something slow. Make it breathe." },
    ],
    closingNote: "Ballads are where your voice shows up. That was yours.",
  },
  {
    id: "p3-a-jazz",
    instrument: "piano",
    phase: 3,
    name: "A minor 7th colour",
    soulName: "Grown-Up Harmony",
    minutes: 6,
    ghostKey: "am",
    pillar: "lead-sheet",
    steps: [
      { type: "progression", durationSec: 45, instruction: "i7–iv7–V7–i7 in A minor (Am7–Dm7–E7–Am7)." },
      { type: "lead-sheet",  durationSec: 60, instruction: "LH: shell voicings (root + 3rd + 7th). RH: rest on beats 1 and 3." },
      { type: "improv",      durationSec: 90, instruction: "RH: A minor scale, landing on chord tones." },
      { type: "song",        durationSec: 60, instruction: "Summertime (Gershwin) — this neighbourhood exactly." },
      { type: "song",        durationSec: 45, instruction: "One chorus of Autumn Leaves, your way." },
    ],
    closingNote: "7ths are the colour of grown-up harmony. You earned them.",
  },
  {
    id: "p3-blues-starter",
    instrument: "piano",
    phase: 3,
    name: "12-bar blues starter",
    soulName: "Blues Permission",
    minutes: 6,
    ghostKey: "C",
    pillar: "improv",
    steps: [
      { type: "progression", durationSec: 60, instruction: "12-bar blues in C: C7 (4 bars) F7 (2) C7 (2) G7 (1) F7 (1) C7 (2)." },
      { type: "progression", durationSec: 60, instruction: "LH: roots only. Feel the 12-bar frame." },
      { type: "improv",      durationSec: 90, instruction: "RH: C minor pentatonic + blue note. Anywhere. Swing eighths." },
      { type: "improv",      durationSec: 60, instruction: "Call and response: LH plays a fill, then RH answers." },
      { type: "song",        durationSec: 30, instruction: "Play any blues lick you've heard. Even one bar. It'll sound right." },
    ],
    closingNote: "You just played blues. You didn't need permission.",
  },
  {
    id: "p3-modulation-test",
    instrument: "piano",
    phase: 3,
    name: "modulation walk",
    soulName: "Walk Between Keys",
    minutes: 6,
    ghostKey: "C",
    pillar: "ear",
    steps: [
      { type: "progression", durationSec: 60, instruction: "Play I–V–vi–IV in C (C–G–Am–F). Once. Cleanly." },
      { type: "progression", durationSec: 60, instruction: "Now do it in G. Then D. Then A. 4 bars each. 1 min total." },
      { type: "improv",      durationSec: 60, instruction: "Improvise 8 bars in whichever key felt best." },
      { type: "song",        durationSec: 60, instruction: "Hey Jude ends modulating. Play that ending. It's a lift." },
      { type: "song",        durationSec: 30, instruction: "Choose a song. Play it up a half step for 4 bars. Weird is OK." },
    ],
    closingNote: "Keys aren't rooms. They're open fields. You walked between them.",
  },
  {
    id: "p3-voice-leading",
    instrument: "piano",
    phase: 3,
    name: "voice leading",
    soulName: "Make the Top Note Sing",
    minutes: 6,
    ghostKey: "F",
    pillar: "expression",
    steps: [
      { type: "progression", durationSec: 60, instruction: "F–Dm–Bb–C. Block chords, root position." },
      { type: "progression", durationSec: 60, instruction: "Now move the top note smoothly across the changes. Minimum movement." },
      { type: "improv",      durationSec: 90, instruction: "RH: lean into the top note as if it's the melody. Make it sing." },
      { type: "song",        durationSec: 60, instruction: "Hikaru Nara (Your Lie in April OP) — voice-leading heaven." },
      { type: "song",        durationSec: 30, instruction: "Play anything — but make the top note the story." },
    ],
    closingNote: "The top voice is the lyric, even without words.",
  },
  {
    id: "p3-pentatonic-fluent",
    instrument: "piano",
    phase: 3,
    name: "pentatonic, fluent",
    soulName: "Solo With Silence",
    minutes: 6,
    ghostKey: "em",
    pillar: "improv",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "E minor pentatonic, hands separate, 2 octaves." },
      { type: "progression", durationSec: 45, instruction: "i–III–VII–VI in Em (Em–G–D–C). LH only." },
      { type: "improv",      durationSec: 120,instruction: "RH: E minor pentatonic. Short phrases first. Then stretch to 4 bars." },
      { type: "improv",      durationSec: 60, instruction: "Add rest — silence is notes too. One bar of music, one bar of nothing." },
      { type: "song",        durationSec: 45, instruction: "La La Land — Mia and Sebastian's theme. E minor cousin." },
    ],
    closingNote: "Improvising with rest is the pro move. You're doing it.",
  },
  {
    id: "p3-sight-read-light",
    instrument: "piano",
    phase: 3,
    name: "sight read, light",
    soulName: "Read It Twice",
    minutes: 5,
    ghostKey: "G",
    pillar: "repertoire",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "G major scale, hands together." },
      { type: "progression", durationSec: 45, instruction: "G–D–Em–C. Block chords LH. Simple." },
      { type: "improv",      durationSec: 60, instruction: "Open a lead sheet from your free-slot URL. Read 4 bars. Be rough." },
      { type: "improv",      durationSec: 60, instruction: "Same 4 bars again. Better this time." },
      { type: "song",        durationSec: 60, instruction: "End on a piece you love, memorised. Anything." },
    ],
    closingNote: "Reading well is reading twice. You did.",
  },

  // ───── Batch 3a — missing fundamentals ─────
  {
    id: "p1-rhythm-foundation",
    instrument: "piano",
    phase: 1,
    name: "rhythm foundation",
    soulName: "Lock the Beat",
    minutes: 9,
    ghostKey: "C",
    pillar: "technique",
    steps: [
      { type: "tone",  durationSec: 60,  instruction: "Set the metronome to 60 BPM. Don't play yet, just tap your foot exactly on every click for about 8 clicks, then relax and reset." },
      { type: "tone",  durationSec: 120, instruction: "Play any single comfortable key exactly on every click, counting out loud '1, 2, 3, 4' the whole time and leaning on the '1' as the downbeat." },
      { type: "tone",  durationSec: 150, instruction: "Same key, same click, but count '1 and 2 and 3 and 4 and' out loud and press the key again on every 'and,' landing it exactly halfway between two clicks." },
      { type: "scale", durationSec: 150, instruction: "Play the five-finger pattern C D E F G, one note per click first, counting the numbers. Then play it again with two notes per click, counting the ands." },
      { type: "song",  durationSec: 60,  instruction: "Raise the metronome to 90 BPM and clap the famous four-note rhythm that opens Beethoven's Symphony No. 5: three short claps then one long one, locked to the new tempo." },
    ],
    closingNote: "Your sense of time just got measurably steadier. That is the pulse everything else in this app stands on.",
  },
  {
    id: "p2-sustain-pedal",
    instrument: "piano",
    phase: 2,
    name: "the syncopated pedal",
    soulName: "Smooth Every Change",
    minutes: 8,
    ghostKey: "am",
    pillar: "technique",
    steps: [
      { type: "tone",        durationSec: 60,  instruction: "Foot on the pedal. Press all the way down, then let it rise all the way up. Ten slow reps, no hands yet. Push from the ankle, not a stomp." },
      { type: "progression", durationSec: 90,  instruction: "Play a C chord, lift your fingers, hear it die. Play it again and press the pedal down right after it lands, not together with it. Feel that small gap." },
      { type: "progression", durationSec: 120, instruction: "Hold the pedal under C. Play F, and right as your hand strikes it, flick the pedal up then straight back down. One flick, C cleared, F caught." },
      { type: "progression", durationSec: 150, instruction: "Loop Am, F, C, G, one chord per bar. Flick the pedal up and down on every single change. Four times around, no gaps, no mud." },
      { type: "song",        durationSec: 60,  instruction: "Play the opening of River Flows in You with the same flick on every chord change. Let the pedal disappear into the sound." },
    ],
    closingNote: "The gap and the mud are both gone now. That flick is the sound behind every ballad you have ever loved.",
  },
  {
    id: "p-t2-inversions-drill",
    instrument: "piano",
    phase: 2,
    name: "chord inversions",
    soulName: "The Nearest Chord",
    minutes: 10,
    ghostKey: "am",
    pillar: "technique",
    steps: [
      { type: "triad",       durationSec: 60,  instruction: "Play C major root position: C, E, G. Then first inversion: E, G, C. Then second inversion: G, C, E." },
      { type: "triad",       durationSec: 90,  instruction: "Tour F (root F, A, C, first inversion A, C, F, second inversion C, F, A), then G (root G, B, D, first inversion B, D, G, second inversion D, G, B)." },
      { type: "progression", durationSec: 240, instruction: "Loop Am to F and back, using F's first inversion (A, C, F), not its root position. Keep your thumb and middle finger resting on A and C the entire time. Only the top finger climbs from E to F and back." },
      { type: "progression", durationSec: 150, instruction: "Try F to C the same way. Play F root position, then hunt for whichever C shape keeps your hand closest, instead of leaping to C's root position. Let your ear confirm when it feels smooth." },
      { type: "song",        durationSec: 60,  instruction: "Play the Am to F change from the chorus of Let It Be (The Beatles), using the first inversion. Notice how small the motion feels now." },
    ],
    closingNote: "Your chord changes just got quieter. That is what smooth voice leading actually sounds like.",
  },
  {
    id: "p2-lh-patterns",
    instrument: "piano",
    phase: 2,
    name: "Left-hand accompaniment patterns",
    soulName: "The Left Hand Wakes Up",
    minutes: 9,
    ghostKey: "C",
    pillar: "technique",
    steps: [
      { type: "triad",        durationSec: 60,  instruction: "Play a C block chord (C, E, G), then break it apart: C, E, G, C, one note at a time, up and back down." },
      { type: "parallel-set", durationSec: 90,  instruction: "Root-fifth pattern: alternate just C and G, the root and fifth, leaving out the E, for four bars." },
      { type: "parallel-set", durationSec: 120, instruction: "Rolling arpeggio: root, fifth, octave, fifth (C, G, C, G), repeating in a steady loop for four bars." },
      { type: "parallel-set", durationSec: 120, instruction: "Octave bass: alternate low C with the C an octave higher, four bars, leaning into the low note each time." },
      { type: "progression",  durationSec: 150, instruction: "Loop C, F, G, C, choosing a different left-hand pattern for each chord while the right hand plays the melody from Chord Under Melody." },
    ],
    closingNote: "Your left hand just learned to move. That is the sound of a real accompanist, not a stuck chord.",
  },

  // ───── Batch 3b — hands-together, more keys, articulation, whole song ─────
  {
    id: "p1-articulation",
    instrument: "piano",
    phase: 1,
    name: "legato vs staccato",
    soulName: "Smooth or Crisp",
    minutes: 7,
    ghostKey: "C",
    pillar: "expression",
    steps: [
      { type: "scale", durationSec: 90,  instruction: "Play the five-finger pattern C D E F G legato: hold each key down right until the next finger presses, so there is never a gap. Smooth and connected. Up and back down, twice." },
      { type: "scale", durationSec: 90,  instruction: "Now the same C D E F G staccato: release each key the instant you press it, a little silence between every note. Short and detached. Up and back down, twice." },
      { type: "scale", durationSec: 90,  instruction: "Alternate: play the pattern legato once, then staccato once, back and forth. Same notes, same tempo, only the touch changes." },
      { type: "moods", durationSec: 90,  instruction: "Play a tiny known melody (Twinkle Twinkle: C C G G A A G) fully legato, then fully staccato. Hear it flip from lullaby to music box." },
      { type: "song",  durationSec: 60,  instruction: "Für Elise opening: play its run smooth and legato, then clip a few notes staccato. Feel how articulation shapes the character." },
    ],
    closingNote: "Same notes, two feelings, and you are choosing which. That is expression, not just accuracy.",
  },
  {
    id: "p2-hands-together",
    instrument: "piano",
    phase: 2,
    name: "hands together + left-hand fingering",
    soulName: "Both Hands, One Scale",
    minutes: 10,
    ghostKey: "C",
    pillar: "technique",
    steps: [
      { type: "scale", durationSec: 90,  instruction: "Left hand alone, C major up: pinky (5) on low C, then 4, 3, 2, thumb (1) on G, then cross the THIRD finger over the thumb onto A, then 2, then thumb on top C. Fingers: 5-4-3-2-1-3-2-1. Slow." },
      { type: "scale", durationSec: 60,  instruction: "Left-hand C scale up and back down a few times. Watch the third-finger cross-over land smoothly on A going up. No lurch." },
      { type: "scale", durationSec: 60,  instruction: "Right hand alone, the fingering you know: thumb on C, 2, 3, tuck the thumb under after E onto F, then 2, 3, 4, 5. Fingers: 1-2-3-1-2-3-4-5." },
      { type: "scale", durationSec: 150, instruction: "Hands together, VERY slow, one note at a time up the C scale, saying each note out loud as both hands play it. Then back down. Repeat until steady." },
      { type: "scale", durationSec: 120, instruction: "Now G major hands together, same coordination, remembering the F sharp in BOTH hands. Slow and even." },
    ],
    closingNote: "Both hands now climb the same ladder together. That coordination is what every real piece is built on.",
    repBlocks: { repsPerBlock: 3, restSec: 12 },
    bpmLadder: { startBpm: 50, targetBpm: 90, step: 5, advanceAfterSuccesses: 3 },
  },
  {
    id: "p2-a-major",
    instrument: "piano",
    phase: 2,
    name: "A major bright",
    soulName: "Bright and Ringing",
    minutes: 5,
    ghostKey: "A",
    pillar: "repertoire",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "A major scale, right hand up: A, B, C#, D, E, F#, G#, A. Three sharps (F#, C#, G#), the black keys above F, C, G. Thumb tucks after C#." },
      { type: "triad",       durationSec: 30, instruction: "A major triad: A, C#, E together. Thumb, middle, pinky. Bright and full." },
      { type: "progression", durationSec: 60, instruction: "I–V–vi–IV in A: A, E, F#m (F# A C#), D. Four counts each. The classic uplifting pop cycle in a brighter home." },
      { type: "improv",      durationSec: 90, instruction: "Right hand, A major pentatonic (A B C# E F#). Aim for an 8-bar melody. Land on A to come home." },
      { type: "song",        durationSec: 45, instruction: "Take Me Home, Country Roads (John Denver) — A, F#m, E, D. Its whole singalong lives in A major." },
    ],
    closingNote: "Three sharps, same fingers as always. A major is the ringing home of a thousand singalongs.",
  },
  {
    id: "p2-e-major",
    instrument: "piano",
    phase: 2,
    name: "E major anthem",
    soulName: "The Anthem Key",
    minutes: 5,
    ghostKey: "E",
    pillar: "repertoire",
    steps: [
      { type: "scale",       durationSec: 30, instruction: "E major scale, right hand up: E, F#, G#, A, B, C#, D#, E. Four sharps (F#, G#, C#, D#). Thumb tucks after G#." },
      { type: "triad",       durationSec: 30, instruction: "E major triad: E, G#, B together. Thumb, middle, pinky. Big and bright, ringing like a bell." },
      { type: "progression", durationSec: 60, instruction: "I–V–vi–IV in E: E, B, C#m (C# E G#), A. Four counts each. The anthem cycle." },
      { type: "improv",      durationSec: 90, instruction: "Right hand, E major pentatonic (E F# G# B C#). Stretch to an 8-bar phrase, ending on E." },
      { type: "song",        durationSec: 45, instruction: "Don't Stop Believin' (Journey) — its verse loops E, B, C#m, A. One of the most famous singalongs ever, right here in E major." },
    ],
    closingNote: "Four sharps and still the same pattern. E major is where the biggest anthems live.",
  },
  {
    id: "p2-first-song",
    instrument: "piano",
    phase: 2,
    name: "play a whole song",
    soulName: "Your First Whole Song",
    minutes: 12,
    ghostKey: "C",
    pillar: "repertoire",
    steps: [
      { type: "song", durationSec: 60,  instruction: "Choose ONE song you can mostly handle: one the app has suggested for the chords you know, or a simple song of your own. Pick something you love, not something impressive." },
      { type: "song", durationSec: 180, instruction: "Break it into sections (verse, chorus, bridge). Learn each section hands-separate first, then hands together, one at a time. Do not move on until a section flows." },
      { type: "song", durationSec: 180, instruction: "Stitch the sections together, playing one straight into the next, slow enough that you never stop to think. Smooth out the seams." },
      { type: "song", durationSec: 180, instruction: "Play the WHOLE song start to finish at a slow steady tempo without stopping, even through wrong notes. Reach the final note no matter what." },
      { type: "song", durationSec: 60,  instruction: "Make a note to do one more full run-through on your NEXT session too. Two complete passes on two days means you truly own it." },
    ],
    closingNote: "You just played a whole song, start to finish, both hands. That is not practice anymore. That is playing.",
  },

  // ───── Curriculum #2 — timed chord-transition fluency ─────
  // A TRANSITION drill (transitionPairId set): the slot renders the 60-second
  // clean-change counter, not the rep engine. Clearing ~30/min marks p-trans-am-F
  // learned, which gates The Pop Formula.
  {
    id: "p-trans-am-F-drill",
    instrument: "piano",
    phase: 2,
    name: "Am → F, one-minute changes",
    soulName: "The Last Reps Before the Song",
    minutes: 2,
    ghostKey: "am",
    pillar: "technique",
    transitionPairId: "am-F",
    steps: [
      { type: "progression", durationSec: 60, instruction: "Switch Am↔F cleanly for 60 seconds. Tap each clean landing. Target 30." },
    ],
    closingNote: "The count going up IS the progress. Beat your last number, that's it.",
  },
];

export const CHAIN_DRILLS: ChainDrill[] = withDefaultMotorConfigAll(RAW_CHAIN_DRILLS);

export function findDrill(id: string) {
  return CHAIN_DRILLS.find((d) => d.id === id);
}
