// Piano skill-tree DAG — PIANO_NODES.
//
// A real, coherent prereq graph (not stubs). Guitar (P4) is the showcase tree;
// piano is intentionally a lighter set, but every edge is real and the graph is
// acyclic + fully reachable from the tier-0 roots.
//
// Design axes mapped from the existing app:
//   - the 12 unlock cards (lib/piano/unlocks.ts) → each maps to the node whose
//     completion earns it, via `unlock` (the capability sentence is carried here
//     and on the card; the linkage is by id convention "u-<node-suffix>").
//   - the key-depth concept (KeyDepth 0..5 per key) → per-key foundation nodes
//     (p-key-C, p-key-am, ...) tagged with `keyId` so a future surface can tie
//     node progress to keyDepths.
//   - chain-drill pillars (technique / ear / expression / lead-sheet / improv /
//     repertoire) → SkillCategory + chainDrillId links to concrete drills.
//
// Tiers (sunrise ramp, shared with guitar):
//   t0 orientation · t1 foundation + first keys · t2 more keys + improv + ear ·
//   t3 lead-sheet / jazz / expression.

import type { SkillNode } from "../types";

// V4 soul-first labels + path membership applied per docs/research/soul-first-learning.md
// Section 3 (piano table). The four foundation keys (C/G/F/am) are on all three paths
// and are NOT theory (a beginner needs a home key to play in). Reading-the-staff,
// lead-sheet, and ii-V-I are the only piano theory:true nodes; they carry NO soulTitle
// (they only render in Go Deep, where the theory name is the right label). All fields
// optional and backward-compatible.

export const PIANO_NODES: SkillNode[] = [
  // ───── Tier 0 — orientation ─────
  {
    id: "p-t0-keyboard-map",
    instrument: "piano",
    title: "Map the Keyboard",
    tier: 0,
    category: "setup",
    prereqs: [],
    masteryDrill: "Close your eyes, pick a letter, touch it in under a second.",
    unlock: "Find any note in under a second.",
    unlockCardId: "u-p1-keyboard-map",
    soulTitle: "Find Any Note",
    keepTitle: "Keyboard Map",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "p-t0-posture",
    instrument: "piano",
    title: "Posture & Arm Weight",
    tier: 0,
    category: "technique",
    prereqs: ["p-t0-keyboard-map"],
    masteryDrill: "Five-finger pattern with relaxed arm weight, zero tension between strikes.",
    unlock: "Play without tension — the foundation of tone.",
    soulTitle: "Sit and Settle",
    keepTitle: "Posture and Arm Weight",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "p-t0-staff",
    instrument: "piano",
    title: "Reading the Staff",
    tier: 0,
    category: "notation",
    prereqs: ["p-t0-keyboard-map"],
    masteryDrill: "Name treble + bass clef notes on sight, no counting up from a landmark.",
    unlock: "Decode a basic score.",
    keepTitle: "Reading the Staff",
    pathTags: ["go-deep"],
    theory: true,
  },

  // ───── Tier 1 — foundation + first keys ─────
  {
    id: "p-key-C",
    instrument: "piano",
    title: "C major is yours",
    tier: 1,
    category: "scales",
    prereqs: ["p-t0-posture"],
    masteryDrill: "C scale hands-separate, C triad, I–IV–V–I in C.",
    unlock: "C major is yours.",
    chainDrillId: "p1-c-major-chain",
    keyId: "C",
    unlockCardId: "u-p1-c-map",
    fluencyTest: { prompt: "Play the C major scale, hands together, while counting the beats out loud." },
    soulTitle: "The Home Shape",
    keepTitle: "C major",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "p-key-G",
    instrument: "piano",
    title: "G major (one sharp)",
    tier: 1,
    category: "scales",
    prereqs: ["p-key-C"],
    masteryDrill: "G scale hands-separate — listen for the F♯. G triad, G–C–D–G.",
    unlock: "A second key under your hands.",
    chainDrillId: "p1-g-major-chain",
    keyId: "G",
    soulTitle: "One Sharp",
    keepTitle: "G major (one sharp)",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "p-key-F",
    instrument: "piano",
    title: "F major (one flat)",
    tier: 1,
    category: "scales",
    prereqs: ["p-key-C"],
    masteryDrill: "F scale, thumb on F and C. F triad, F–Bb–C–F.",
    unlock: "The home key of countless ballads.",
    chainDrillId: "p1-f-major-chain",
    keyId: "F",
    soulTitle: "One Flat",
    keepTitle: "F major (one flat)",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "p-key-am",
    instrument: "piano",
    title: "A minor longing",
    tier: 1,
    category: "scales",
    prereqs: ["p-key-C"],
    masteryDrill: "A natural minor, Am triad, i–iv–V–i. Feel the E resolve.",
    unlock: "Hear major vs minor reliably.",
    chainDrillId: "p1-a-minor-chain",
    keyId: "am",
    unlockCardId: "u-p1-minor-feeling",
    soulTitle: "The Sad Shape",
    keepTitle: "A minor",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "p-t1-first-improv",
    instrument: "piano",
    title: "First Improvisation",
    tier: 1,
    category: "expression",
    prereqs: ["p-key-C"],
    masteryDrill: "Loop C–F–G–C with the left hand, noodle C pentatonic with the right.",
    unlock: "Make something up that sounds good.",
    chainDrillId: "p1-c-major-chain",
    unlockCardId: "u-p1-first-improv",
    soulTitle: "Make It Up",
    keepTitle: "First Improvisation",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "p-t1-echo-ear",
    instrument: "piano",
    title: "The Echo (ear)",
    tier: 1,
    category: "ear",
    prereqs: ["p-t0-keyboard-map"],
    masteryDrill: "Hear 3–4 notes in C, echo them back. Then with eyes closed.",
    unlock: "Your ear can find notes it just heard.",
    chainDrillId: "p1-echo-ear",
    soulTitle: "Echo It Back",
    keepTitle: "The Echo (ear training)",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "p-t1-three-moods",
    instrument: "piano",
    title: "Three Moods",
    tier: 1,
    category: "expression",
    prereqs: ["p-key-C"],
    masteryDrill: "Play I–vi–IV–V three ways: tender, restless, resigned. Same notes.",
    unlock: "Touch and timing change the whole feeling.",
    chainDrillId: "p1-three-moods-lite",
    soulTitle: "Same Notes, Three Feelings",
    keepTitle: "Three Moods",
    pathTags: ["play-with-soul", "go-deep"],
  },

  // ───── Tier 2 — more keys, the pop formula, transcribing ─────
  {
    id: "p-t2-chord-under-melody",
    instrument: "piano",
    title: "Chord Under Melody",
    tier: 2,
    category: "technique",
    prereqs: ["p-key-C", "p-key-am"],
    masteryDrill: "Left hand holds a chord while the right hand plays a melody.",
    unlock: "Hold a chord with the left hand while the right plays a melody.",
    unlockCardId: "u-p2-chord-under-melody",
    soulTitle: "Two Hands Together",
    keepTitle: "Chord Under Melody",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "p-t2-pop-formula",
    instrument: "piano",
    title: "The Pop Formula",
    tier: 2,
    category: "chords",
    // #2 — gated on the Am→F transition clearing the fluency threshold, so the
    // song unlock fires only once the hard change is actually in tempo.
    prereqs: ["p-t2-chord-under-melody", "p-trans-am-F"],
    masteryDrill: "Am–F–C–G as block chords, then a melody over the loop.",
    unlock: "You can play half of pop music.",
    chainDrillId: "p2-am-pop-formula",
    unlockCardId: "u-p2-pop-formula",
    fluencyTest: { prompt: "Play the Am–F–C–G loop without looking at your hands, and hum the melody on top." },
    soulTitle: "Half of All Pop",
    keepTitle: "The Pop Formula",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "p-t2-4-bar-improv",
    instrument: "piano",
    title: "4-Bar Improv",
    tier: 2,
    category: "expression",
    prereqs: ["p-t1-first-improv", "p-key-am"],
    masteryDrill: "Loop i–iv–V in A minor, improvise eight bars without panicking.",
    unlock: "Improvise a 4-bar idea without panicking.",
    chainDrillId: "p2-left-hand-loop",
    unlockCardId: "u-p2-4-bar-improv",
    soulTitle: "Improvise Without Panic",
    keepTitle: "4-Bar Improvisation",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "p-t2-transcribe",
    instrument: "piano",
    title: "Put a Melody on the Keys",
    tier: 2,
    category: "ear",
    prereqs: ["p-t1-echo-ear", "p-key-C"],
    masteryDrill: "Play Happy Birthday, then Ode to Joy, by ear in C.",
    unlock: "Put a melody you heard onto the piano.",
    chainDrillId: "p2-song-transcribe",
    unlockCardId: "u-p2-first-transcribe",
    soulTitle: "Play It By Ear",
    keepTitle: "Transcribing by Ear",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "p-key-D",
    instrument: "piano",
    title: "D major daylight",
    tier: 2,
    category: "scales",
    prereqs: ["p-key-G"],
    masteryDrill: "D scale (two sharps), I–V–vi–IV in D.",
    unlock: "A bright two-sharp key.",
    chainDrillId: "p2-d-major-daylight",
    keyId: "D",
    soulTitle: "Bright and Wide Open",
    keepTitle: "D major",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "p-key-em",
    instrument: "piano",
    title: "E minor mood",
    tier: 2,
    category: "scales",
    prereqs: ["p-key-am", "p-key-G"],
    masteryDrill: "E natural minor, i–III–VII–VI in Em, played two moods.",
    unlock: "A relative-minor colour to reach for.",
    chainDrillId: "p2-e-minor-mood",
    keyId: "em",
    soulTitle: "Dark and Cinematic",
    keepTitle: "E minor",
    pathTags: ["play-with-soul", "go-deep"],
  },

  // ───── Tier 3 — lead-sheet, jazz, expression ─────
  {
    id: "p-t3-lead-sheet",
    instrument: "piano",
    title: "Read a Lead Sheet",
    tier: 3,
    category: "chords",
    prereqs: ["p-t2-pop-formula", "p-key-G"],
    masteryDrill: "LH comps chord symbols while RH finds the melody, in real time.",
    unlock: "Read a lead sheet in real time.",
    chainDrillId: "p2-g-lead-sheet",
    unlockCardId: "u-p3-lead-sheet",
    keepTitle: "Reading a Lead Sheet",
    pathTags: ["go-deep"],
    theory: true,
  },
  {
    id: "p-t3-three-moods",
    instrument: "piano",
    title: "Same Progression, Three Ways",
    tier: 3,
    category: "expression",
    prereqs: ["p-t1-three-moods", "p-t2-chord-under-melody"],
    masteryDrill: "vi–IV–I–V played tender, angry, resigned — only touch and timing change.",
    unlock: "Play the same progression three ways.",
    chainDrillId: "p2-three-moods",
    unlockCardId: "u-p3-three-moods",
    soulTitle: "Feel, Not Notes",
    keepTitle: "Same Progression, Three Ways",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "p-t3-pop-pull",
    instrument: "piano",
    title: "Pull a Song from a Recording",
    tier: 3,
    category: "ear",
    prereqs: ["p-t2-transcribe", "p-t2-pop-formula"],
    masteryDrill: "Put on a half-known song, find the melody, find a chord under each bar.",
    unlock: "Pick up a pop song from a recording.",
    chainDrillId: "p3-pop-pull",
    unlockCardId: "u-p3-pop-pull",
    soulTitle: "Pull a Song Off a Record",
    keepTitle: "Transcribing Pop Songs",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "p-t3-ii-v-i",
    instrument: "piano",
    title: "ii–V–I (first jazz)",
    tier: 3,
    category: "chords",
    prereqs: ["p-t3-lead-sheet"],
    masteryDrill: "ii–V–I in F and C with shell voicings, melody landing on chord tones.",
    unlock: "You can read and play a ii–V–I.",
    chainDrillId: "p3-ii-v-i-taste",
    unlockCardId: "u-p3-ii-v-i",
    keepTitle: "ii-V-I (jazz foundation)",
    pathTags: ["go-deep"],
    theory: true,
  },
  {
    id: "p-t3-blues",
    instrument: "piano",
    title: "12-Bar Blues",
    tier: 3,
    category: "rhythm",
    prereqs: ["p-t2-4-bar-improv", "p-key-C"],
    masteryDrill: "12-bar blues in C, LH roots, RH C minor pentatonic + blue note, swung.",
    unlock: "Play blues without permission.",
    chainDrillId: "p3-blues-starter",
    soulTitle: "Blues Permission",
    keepTitle: "12-Bar Blues",
    pathTags: ["play-with-soul", "go-deep"],
  },

  // ───── Curriculum #2 — chord-transition fluency (the song bottleneck) ─────
  // A timed one-minute-changes drill on the Am→F pair (the hard change behind
  // the Pop Formula loop). Learned when the pair clears ~30 clean changes/min;
  // it gates The Pop Formula as "the last reps before the song." Prereqs are the
  // two keys the chords live in — no cycle (pop-formula sits above this).
  {
    id: "p-trans-am-F",
    instrument: "piano",
    title: "Am → F, in time",
    tier: 2,
    category: "chords",
    prereqs: ["p-key-C", "p-key-am"],
    masteryDrill: "One-minute changes Am↔F. Count clean changes. Target 30/min.",
    unlock: "Change between Am and F in tempo — the last reps before the song.",
    chainDrillId: "p-trans-am-F-drill",
    soulTitle: "The Last Reps Before the Song",
    keepTitle: "Am → F transition",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
];
