import type { ChainDrill } from "../types";

// Guitar chain drills. The chain logic is identical to piano: every technique
// chains into a real riff/song in the same session (Skill → Shape/Riff →
// Progression → Improv/Song). Drill texts follow the guitar.md drills (one-minute
// changes, chromatic spider, power-chord moves, pentatonic boxes, 12-bar blues).
//
// `id` matches the chainDrillId set on GUITAR_NODES — playing the drill marks the
// node in-progress/learned (gated by its prereq chain in endSession). `ghostKey`
// uses guitar's focus-key set (em/am/E/A/G/C/D), so chainDrillPicker's ghost-key
// preference still works. Phases map to tiers: t0/t1 → 1, t2 → 2, t3 → 3.
//
// ChainStep `type` reuses the shared ChainStepType union; guitar maps:
//   tone → technique reps (picking, fretting, muting, bends)
//   triad → chord shapes (open chords, power chords, barre)
//   scale → pentatonic boxes / chromatic
//   progression → chord changes / 12-bar
//   improv → soloing / phrasing
//   song → the reward riff
export const GUITAR_CHAIN_DRILLS: ChainDrill[] = [
  // ───── PHASE 1 — setup + foundations ─────
  {
    id: "g-t0-tuning-chain",
    instrument: "guitar",
    phase: 1,
    name: "tune & orient",
    minutes: 3,
    ghostKey: "em",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 45, instruction: "Name all six strings aloud: E A D G B E, low to high." },
      { type: "tone", durationSec: 60, instruction: "Tune each string to a tuner, from cold. Target under 90 seconds." },
      { type: "tone", durationSec: 45, instruction: "Pluck each open string slowly, listen. Is it ringing true?" },
      { type: "song", durationSec: 30, instruction: "Play any open string in rhythm — you're holding a tuned guitar now." },
    ],
    closingNote: "Ten minutes out of tune teaches your ears the wrong thing. Always tune first.",
  },
  {
    id: "g-t0-tab-chain",
    instrument: "guitar",
    phase: 1,
    name: "read the tab",
    minutes: 3,
    ghostKey: "em",
    pillar: "lead-sheet",
    steps: [
      { type: "tone", durationSec: 45, instruction: "Six lines = six strings. Bottom line is the thick low E. Numbers are frets." },
      { type: "tone", durationSec: 60, instruction: "Open the Seven Nation Army tab. Say each fret number aloud, left to right." },
      { type: "tone", durationSec: 45, instruction: "Find the bar lines. A vertical stack of numbers = play those strings together." },
      { type: "song", durationSec: 30, instruction: "You just read a riff off the page — no ears needed. The whole internet of tab is open now." },
    ],
    closingNote: "Tab is the guitar's lead sheet. Read the numbers, find the frets. That's the whole code.",
  },
  {
    id: "g-t1-fretting-chain",
    instrument: "guitar",
    phase: 1,
    name: "clean fretting",
    minutes: 3,
    ghostKey: "em",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 60, instruction: "Press fret 1 on every string. Each must ring clean — fingertip, not pad." },
      { type: "tone", durationSec: 60, instruction: "Walk up to fret 5 and back, one string at a time. No buzz." },
      { type: "tone", durationSec: 30, instruction: "Thumb behind the neck the whole time. Lightest pressure that rings." },
      { type: "song", durationSec: 30, instruction: "Play the first three notes of any melody, clean." },
    ],
    closingNote: "Death-grip is the #1 beginner error. Relax the thumb. Let the fingertip do the work.",
  },
  {
    id: "g-t1-downpick-chain",
    instrument: "guitar",
    phase: 1,
    name: "down-picking",
    minutes: 3,
    ghostKey: "em",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 60, instruction: "Open low E, downstrokes at 60bpm. Quarter notes. Even volume." },
      { type: "tone", durationSec: 60, instruction: "Move to open A, then open D. Same even attack. Pick at ~45°." },
      { type: "tone", durationSec: 30, instruction: "Loose wrist — the motion comes from the wrist, not the arm." },
      { type: "song", durationSec: 30, instruction: "Seven Nation Army main riff — one string, all downstrokes." },
    ],
    closingNote: "You can't play this wrong. Even and relaxed beats fast and tense every time.",
    // V3 seed: micro-rest cadence + tempo ladder; eligible for interleaving.
    repBlocks: { repsPerBlock: 3, restSec: 12 },
    bpmLadder: { startBpm: 60, targetBpm: 120, step: 5, advanceAfterSuccesses: 3 },
    interleavable: true,
  },
  {
    id: "g-t1-altpick-chain",
    instrument: "guitar",
    phase: 1,
    name: "alternate picking",
    minutes: 3,
    ghostKey: "em",
    pillar: "technique",
    steps: [
      { type: "scale", durationSec: 90, instruction: "Chromatic 1-2-3-4 on the low E, alternate down-up-down-up at 80bpm." },
      { type: "scale", durationSec: 60, instruction: "Carry the 1-2-3-4 across all six strings, one pass = one rep." },
      { type: "tone", durationSec: 30, instruction: "Strict alternation — never two downs in a row." },
      { type: "song", durationSec: 30, instruction: "Play a short melody using alternate picking. Smoke on the Water works." },
    ],
    closingNote: "Down-up is the engine of every fast line. Learn it now, not after the bad habits.",
    // V3 seed: micro-rest cadence + tempo ladder; eligible for interleaving.
    repBlocks: { repsPerBlock: 3, restSec: 12 },
    bpmLadder: { startBpm: 80, targetBpm: 140, step: 5, advanceAfterSuccesses: 3 },
    interleavable: true,
  },
  {
    id: "g-t1-open-chords-em-chain",
    instrument: "guitar",
    phase: 1,
    name: "open chords: Em/Am/E/A",
    minutes: 4,
    ghostKey: "em",
    pillar: "technique",
    steps: [
      { type: "triad", durationSec: 45, instruction: "Form Em, then Am. Every string in each chord rings clean." },
      { type: "progression", durationSec: 90, instruction: "One-minute changes Em↔Am — count clean swaps. Target 30+." },
      { type: "progression", durationSec: 60, instruction: "One-minute changes E↔A. Write the count down." },
      { type: "song", durationSec: 45, instruction: "Knockin' on Heaven's Door uses Em and a friend. Strum through a verse." },
    ],
    closingNote: "The count going up is the progress. Beat yesterday's number, that's it.",
  },
  {
    id: "g-t1-open-chords-dgc-chain",
    instrument: "guitar",
    phase: 1,
    name: "open chords: D/G/C",
    minutes: 4,
    ghostKey: "G",
    pillar: "technique",
    steps: [
      { type: "triad", durationSec: 45, instruction: "Form D (triangle), G (4-finger), C (arc). All strings ring." },
      { type: "progression", durationSec: 90, instruction: "One-minute changes G↔C — the hard one. Count clean swaps." },
      { type: "progression", durationSec: 60, instruction: "Once G↔C hits 30/min, add D↔G changes." },
      { type: "song", durationSec: 45, instruction: "Wonderwall lives in Em, G, D, A. Try the intro progression." },
    ],
    closingNote: "Seven open chords cover most of pop and rock. You almost have them all.",
  },
  {
    id: "g-t1-strum-chain",
    instrument: "guitar",
    phase: 1,
    name: "strumming",
    minutes: 4,
    ghostKey: "em",
    pillar: "expression",
    steps: [
      { type: "progression", durationSec: 60, instruction: "Em→Am→C→G, one bar each, down-strums only at 80bpm." },
      { type: "progression", durationSec: 60, instruction: "Same loop, add D-DU (down, down-up). Keep it relaxed." },
      { type: "progression", durationSec: 60, instruction: "Now the folk strum: D-DU-UDU over the loop." },
      { type: "song", durationSec: 60, instruction: "Strum any song you half-know with the folk pattern. It'll sound musical." },
    ],
    closingNote: "Rhythm is the first thing listeners hear. A clean chord in time sounds like music.",
  },
  {
    id: "g-t1-power-chords-chain",
    instrument: "guitar",
    phase: 1,
    name: "power chords",
    minutes: 4,
    ghostKey: "E",
    pillar: "technique",
    steps: [
      { type: "triad", durationSec: 45, instruction: "Form E5 (low E + 2nd fret A). Two fingers. Slide the shape up." },
      { type: "progression", durationSec: 75, instruction: "E5→A5→D5→G5, two beats each at 80bpm. The shape never changes." },
      { type: "progression", durationSec: 60, instruction: "Move E5 up to F5, then up in half-steps to the 5th fret." },
      { type: "song", durationSec: 60, instruction: "Iron Man riff — it's E5/G5/A5/D5. Play it slow and heavy." },
    ],
    closingNote: "One moveable shape = the whole rock vocabulary. This is the electric guitar sound.",
    // V3 seed: micro-rest cadence + tempo ladder; eligible for interleaving.
    repBlocks: { repsPerBlock: 3, restSec: 12 },
    bpmLadder: { startBpm: 80, targetBpm: 120, step: 5, advanceAfterSuccesses: 3 },
    interleavable: true,
  },
  {
    id: "g-t1-palmmute-chain",
    instrument: "guitar",
    phase: 1,
    name: "palm muting",
    minutes: 3,
    ghostKey: "E",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 45, instruction: "Rest the pick-hand heel on the strings at the bridge. Chunky, short sound." },
      { type: "tone", durationSec: 60, instruction: "2 bars muted E5, 2 bars open E5, at 80bpm. Audible contrast at each switch." },
      { type: "tone", durationSec: 30, instruction: "Lift slightly for open, settle back for muted. Control the on/off." },
      { type: "song", durationSec: 45, instruction: "Come As You Are — palm-muted throughout. Try the main riff muted." },
    ],
    closingNote: "Muting turns power chords from loud into rhythmic. The defining punk/metal texture.",
  },

  // ───── PHASE 2 — early intermediate ─────
  {
    id: "g-t2-legato-chain",
    instrument: "guitar",
    phase: 2,
    name: "hammer-ons & pull-offs",
    minutes: 4,
    ghostKey: "am",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 60, instruction: "G string 5h7 — pick fret 5, hammer to fret 7 with no second pick. Equal volume." },
      { type: "tone", durationSec: 60, instruction: "G string 7p5 — pick fret 7, pull off to 5 so it rings. 10 reps per string." },
      { type: "scale", durationSec: 60, instruction: "Combine: 5h7p5 across the strings. Smooth, even, legato." },
      { type: "song", durationSec: 60, instruction: "Sunshine of Your Love riff uses a hammer-on. Play it with the open-E drone." },
    ],
    closingNote: "Legato is how a solo flows instead of stutters. Equal volume is the goal.",
  },
  {
    id: "g-t2-bend-vibrato-chain",
    instrument: "guitar",
    phase: 2,
    name: "bends & vibrato",
    minutes: 4,
    ghostKey: "am",
    pillar: "expression",
    steps: [
      { type: "tone", durationSec: 75, instruction: "B string fret 7, bend up until it matches the pitch of fret 9. In tune, 8/10." },
      { type: "tone", durationSec: 60, instruction: "Add vibrato: fret 7, even oscillation, 4 wobbles per beat at 60bpm." },
      { type: "improv", durationSec: 60, instruction: "Bend, hold, add vibrato at the top. Let the note breathe and sing." },
      { type: "song", durationSec: 45, instruction: "Whole Lotta Love — Page's riff is pentatonic with blues bends. Try it." },
    ],
    closingNote: "The bend is the blues voice. A note that breathes beats a note that's just correct.",
  },
  {
    id: "g-t2-pentatonic-box1-chain",
    instrument: "guitar",
    phase: 2,
    name: "minor pentatonic: Box 1",
    minutes: 5,
    ghostKey: "am",
    pillar: "improv",
    steps: [
      { type: "scale", durationSec: 90, instruction: "Am pentatonic Box 1, ascending and descending at 100bpm. Alternate-picked." },
      { type: "scale", durationSec: 60, instruction: "Land on the root (A) at the start and end. Hear home." },
      { type: "improv", durationSec: 120, instruction: "Put on an Am backing track. Improvise for 2 minutes using only Box 1." },
      { type: "song", durationSec: 30, instruction: "Anything you play in this box over Am sounds like a solo. Prove it." },
    ],
    closingNote: "Your first improv vocabulary. Five notes, infinite phrases. You can solo now.",
  },
  {
    id: "g-t2-pentatonic-box2-chain",
    instrument: "guitar",
    phase: 2,
    name: "pentatonic: Box 2 + connect",
    minutes: 4,
    ghostKey: "am",
    pillar: "improv",
    steps: [
      { type: "scale", durationSec: 75, instruction: "Am pentatonic Box 2, ascending/descending at 80bpm." },
      { type: "scale", durationSec: 75, instruction: "Box 1 → Box 2 unbroken, then descend back. One smooth line." },
      { type: "improv", durationSec: 90, instruction: "Improvise over Am, moving between Box 1 and Box 2. Leave first position." },
      { type: "song", durationSec: 30, instruction: "A two-box solo covers more of the neck. Hear the range open up." },
    ],
    closingNote: "Connecting boxes is how you stop being stuck in one spot. The neck opens up.",
  },
  {
    id: "g-t2-barre-e-chain",
    instrument: "guitar",
    phase: 2,
    name: "barre chords: E shape",
    minutes: 4,
    ghostKey: "E",
    pillar: "technique",
    steps: [
      { type: "triad", durationSec: 75, instruction: "F major barre at fret 1 (E-shape). All six strings must ring." },
      { type: "progression", durationSec: 90, instruction: "Slide the E-shape: one-minute changes Bm↔F#m. Target 15+." },
      { type: "tone", durationSec: 30, instruction: "Roll the index slightly onto its side for a cleaner barre." },
      { type: "song", durationSec: 45, instruction: "Any song in F is now playable with one shape. Try a verse." },
    ],
    closingNote: "Every major and minor chord through one moveable shape. The fretboard just got smaller.",
  },
  {
    id: "g-t2-barre-a-chain",
    instrument: "guitar",
    phase: 2,
    name: "barre chords: A shape",
    minutes: 4,
    ghostKey: "A",
    pillar: "technique",
    steps: [
      { type: "triad", durationSec: 75, instruction: "B major barre at fret 2 (A-shape). Top five strings ring clean." },
      { type: "progression", durationSec: 90, instruction: "One-minute changes B↔E using E-shape and A-shape. Target 15+." },
      { type: "tone", durationSec: 30, instruction: "Combine shapes: any chord, anywhere, two ways to play it." },
      { type: "song", durationSec: 45, instruction: "A song that changes key is now no harder. Play one in any key." },
    ],
    closingNote: "Two barre shapes = any chord, any key, anywhere on the neck. Total freedom.",
  },

  // ───── PHASE 3 — intermediate rewards ─────
  {
    id: "g-t3-blues12-chain",
    instrument: "guitar",
    phase: 3,
    name: "12-bar blues",
    minutes: 6,
    ghostKey: "A",
    pillar: "repertoire",
    steps: [
      { type: "progression", durationSec: 120, instruction: "12-bar in A: A5 (4 bars), D5 (2), A5 (2), E5 (1), D5 (1), A5 (2). 75bpm." },
      { type: "tone", durationSec: 30, instruction: "Add a shuffle feel — long-short, long-short. The blues swing." },
      { type: "improv", durationSec: 120, instruction: "Loop the 12-bar, solo over it with Am pentatonic Box 1." },
      { type: "song", durationSec: 60, instruction: "You're now playing rhythm AND lead over a real form. La Grange is right here." },
    ],
    closingNote: "The harmonic spine of blues and rock. You can sit in with a band now.",
  },
  {
    id: "g-t3-phrasing-chain",
    instrument: "guitar",
    phase: 3,
    name: "lead phrasing: call & answer",
    minutes: 5,
    ghostKey: "am",
    pillar: "expression",
    steps: [
      { type: "improv", durationSec: 90, instruction: "Play a 4-note phrase. Then one full bar of silence. Resist filling it." },
      { type: "improv", durationSec: 90, instruction: "Answer the phrase with another 4 notes — like a conversation." },
      { type: "improv", durationSec: 90, instruction: "Over a 12-bar loop: question, silence, answer, repeat. Breathe." },
      { type: "song", durationSec: 30, instruction: "The space is the music. A solo with rests sounds composed, not frantic." },
    ],
    closingNote: "Silence is part of the phrase. Q&A is what makes notes sound like a story.",
  },
  {
    id: "g-t3-licks-chain",
    instrument: "guitar",
    phase: 3,
    name: "pentatonic licks: Box 1",
    minutes: 5,
    ghostKey: "am",
    pillar: "improv",
    steps: [
      { type: "scale", durationSec: 90, instruction: "Learn 3 classic Box 1 licks. Memorize each one cold." },
      { type: "scale", durationSec: 90, instruction: "Transpose each lick to 2 keys — move the box, the shape holds." },
      { type: "improv", durationSec: 90, instruction: "Drop your licks into an improv over Am. Connect them with bends." },
      { type: "song", durationSec: 30, instruction: "A vocabulary of licks is how real solos get built. You have one now." },
    ],
    closingNote: "Licks are sentences. Memorize a few, then start writing your own with them.",
  },
  {
    id: "g-t3-fullneck-chain",
    instrument: "guitar",
    phase: 3,
    name: "full-neck pentatonic",
    minutes: 6,
    ghostKey: "am",
    pillar: "improv",
    steps: [
      { type: "scale", durationSec: 150, instruction: "The Pentatonic Highway: all 5 Am boxes, 5th fret up to the 17th and back." },
      { type: "scale", durationSec: 60, instruction: "Connect each box to the next with a slide. One unbroken line up the neck." },
      { type: "improv", durationSec: 120, instruction: "Improvise over Am moving freely between all five positions." },
      { type: "song", durationSec: 30, instruction: "The whole fretboard is one scale now. No more being stuck in a box." },
    ],
    closingNote: "Full fretboard freedom. The neck is no longer five separate rooms — it's one space.",
  },
  {
    id: "g-t3-syncopation-chain",
    instrument: "guitar",
    phase: 3,
    name: "syncopation & accents",
    minutes: 4,
    ghostKey: "em",
    pillar: "expression",
    steps: [
      { type: "progression", durationSec: 90, instruction: "D-x-DU-x-DU over Em at 90bpm. The 'x' is a muted percussive stroke." },
      { type: "tone", durationSec: 45, instruction: "Keep the muted strokes even — the groove lives in the silences." },
      { type: "progression", durationSec: 75, instruction: "Add accents on the off-beats. Push and pull against the click." },
      { type: "song", durationSec: 60, instruction: "Back in Black — alternating muted and open accents. That's the riff." },
    ],
    closingNote: "Syncopation is what makes a rhythm part feel alive instead of mechanical.",
  },
];
