import type { ChainDrill } from "../types";
import { withDefaultMotorConfigAll } from "../drillConfig";

// V4 soul-first: `soulName` adds a feel-first heading for each drill (e.g.
// "Your First Solo" instead of "minor pentatonic: Box 1"), matching the node
// soulTitles in skillNodes.ts. The theory `name` stays as the fallback.
//
// Guitar chain drills. The chain logic is identical to piano: every technique
// chains into a real riff/song in the same session (Skill → Shape/Riff →
// Progression → Improv/Song). Drill texts follow the guitar.md drills (one-minute
// changes, chromatic spider, power-chord moves, pentatonic boxes, 12-bar blues).
//
// `id` matches the chainDrillId set on GUITAR_NODES — playing the drill marks the
// node in-progress/learned (gated by its prereq chain in endSession). `ghostKey`
// uses guitar's focus-key set (em/am/E/A/G/C/D), so chainDrillPicker's ghost-key
// preference still works. Phases map to tiers: t0/t1 → 1, t2 → 2, t3 → 3.
//
// ChainStep `type` reuses the shared ChainStepType union; guitar maps:
//   tone → technique reps (picking, fretting, muting, bends)
//   triad → chord shapes (open chords, power chords, barre)
//   scale → pentatonic boxes / chromatic
//   progression → chord changes / 12-bar
//   improv → soloing / phrasing
//   song → the reward riff
// Raw authored guitar drills; augmented below (#2) the same way as piano:
// micro-rest cadence for all, a default tempo ladder for tempo-relevant drills.
const RAW_GUITAR_CHAIN_DRILLS: ChainDrill[] = [
  // ───── PHASE 1 — setup + foundations ─────
  {
    id: "g-t0-tuning-chain",
    instrument: "guitar",
    phase: 1,
    name: "tune & orient",
    soulName: "Get In Tune",
    minutes: 3,
    ghostKey: "em",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 45, instruction: "Name all six strings aloud: E A D G B E, low to high." },
      { type: "tone", durationSec: 60, instruction: "Tune each string to a tuner, from cold. Target under 90 seconds." },
      { type: "tone", durationSec: 45, instruction: "Pluck each open string slowly, listen. Is it ringing true?" },
      { type: "song", durationSec: 30, instruction: "Play any open string in rhythm — you're holding a tuned guitar now." },
    ],
    closingNote: "Ten minutes out of tune teaches your ears the wrong thing. Always tune first.",
  },
  {
    id: "g-t0-tab-chain",
    instrument: "guitar",
    phase: 1,
    name: "read the tab",
    soulName: "Read the Map",
    minutes: 3,
    ghostKey: "em",
    pillar: "lead-sheet",
    steps: [
      { type: "tone", durationSec: 45, instruction: "Six lines = six strings. Bottom line is the thick low E. Numbers are frets." },
      { type: "tone", durationSec: 60, instruction: "Open the Seven Nation Army tab. Say each fret number aloud, left to right." },
      { type: "tone", durationSec: 45, instruction: "Find the bar lines. A vertical stack of numbers = play those strings together." },
      { type: "song", durationSec: 30, instruction: "You just read a riff off the page — no ears needed. The whole internet of tab is open now." },
    ],
    closingNote: "Tab is the guitar's lead sheet. Read the numbers, find the frets. That's the whole code.",
  },
  {
    id: "g-t1-fretting-chain",
    instrument: "guitar",
    phase: 1,
    name: "clean fretting",
    soulName: "Clean Notes",
    minutes: 3,
    ghostKey: "em",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 60, instruction: "Press fret 1 on every string. Each must ring clean — fingertip, not pad." },
      { type: "tone", durationSec: 60, instruction: "Walk up to fret 5 and back, one string at a time. No buzz." },
      { type: "tone", durationSec: 30, instruction: "Thumb behind the neck the whole time. Lightest pressure that rings." },
      { type: "song", durationSec: 30, instruction: "Play the first three notes of any melody, clean." },
    ],
    closingNote: "Death-grip is the #1 beginner error. Relax the thumb. Let the fingertip do the work.",
  },
  {
    id: "g-t1-downpick-chain",
    instrument: "guitar",
    phase: 1,
    name: "down-picking",
    soulName: "Hit It Once",
    minutes: 3,
    ghostKey: "em",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 60, instruction: "Open low E, downstrokes at 60bpm. Quarter notes. Even volume." },
      { type: "tone", durationSec: 60, instruction: "Move to open A, then open D. Same even attack. Pick at ~45°." },
      { type: "tone", durationSec: 30, instruction: "Loose wrist — the motion comes from the wrist, not the arm." },
      { type: "song", durationSec: 30, instruction: "Seven Nation Army main riff — one string, all downstrokes." },
    ],
    closingNote: "You can't play this wrong. Even and relaxed beats fast and tense every time.",
    // V3 seed: micro-rest cadence + tempo ladder; eligible for interleaving.
    repBlocks: { repsPerBlock: 3, restSec: 12 },
    bpmLadder: { startBpm: 60, targetBpm: 120, step: 5, advanceAfterSuccesses: 3 },
    interleavable: true,
  },
  {
    id: "g-t1-altpick-chain",
    instrument: "guitar",
    phase: 1,
    name: "alternate picking",
    soulName: "Pick in Both Directions",
    minutes: 3,
    ghostKey: "em",
    pillar: "technique",
    steps: [
      { type: "scale", durationSec: 90, instruction: "Chromatic 1-2-3-4 on the low E, alternate down-up-down-up at 80bpm." },
      { type: "scale", durationSec: 60, instruction: "Carry the 1-2-3-4 across all six strings, one pass = one rep." },
      { type: "tone", durationSec: 30, instruction: "Strict alternation — never two downs in a row." },
      { type: "song", durationSec: 30, instruction: "Play a short melody using alternate picking. Smoke on the Water works." },
    ],
    closingNote: "Down-up is the engine of every fast line. Learn it now, not after the bad habits.",
    // V3 seed: micro-rest cadence + tempo ladder; eligible for interleaving.
    repBlocks: { repsPerBlock: 3, restSec: 12 },
    bpmLadder: { startBpm: 80, targetBpm: 140, step: 5, advanceAfterSuccesses: 3 },
    interleavable: true,
  },
  {
    id: "g-t1-open-chords-em-chain",
    instrument: "guitar",
    phase: 1,
    name: "open chords: Em/Am/E/A",
    soulName: "The Minor Heart",
    minutes: 4,
    ghostKey: "em",
    pillar: "technique",
    steps: [
      { type: "triad", durationSec: 45, instruction: "Form Em, then Am. Every string in each chord rings clean." },
      { type: "progression", durationSec: 90, instruction: "One-minute changes Em↔Am — count clean swaps. Target 30+." },
      { type: "progression", durationSec: 60, instruction: "One-minute changes E↔A. Write the count down." },
      { type: "song", durationSec: 45, instruction: "Knockin' on Heaven's Door uses Em and a friend. Strum through a verse." },
    ],
    closingNote: "The count going up is the progress. Beat yesterday's number, that's it.",
  },
  {
    id: "g-t1-open-chords-dgc-chain",
    instrument: "guitar",
    phase: 1,
    name: "open chords: D/G/C",
    soulName: "The Full Chord Set",
    minutes: 4,
    ghostKey: "G",
    pillar: "technique",
    steps: [
      { type: "triad", durationSec: 45, instruction: "Form D (triangle), G (4-finger), C (arc). All strings ring." },
      { type: "progression", durationSec: 90, instruction: "One-minute changes G↔C — the hard one. Count clean swaps." },
      { type: "progression", durationSec: 60, instruction: "Once G↔C hits 30/min, add D↔G changes." },
      { type: "song", durationSec: 45, instruction: "Wonderwall lives in Em, G, D, A. Try the intro progression." },
    ],
    closingNote: "Seven open chords cover most of pop and rock. You almost have them all.",
  },
  {
    id: "g-t1-strum-chain",
    instrument: "guitar",
    phase: 1,
    name: "strumming",
    soulName: "The Strum Pattern",
    minutes: 4,
    ghostKey: "em",
    pillar: "expression",
    steps: [
      { type: "progression", durationSec: 60, instruction: "Em→Am→C→G, one bar each, down-strums only at 80bpm." },
      { type: "progression", durationSec: 60, instruction: "Same loop, add D-DU (down, down-up). Keep it relaxed." },
      { type: "progression", durationSec: 60, instruction: "Now the folk strum: D-DU-UDU over the loop." },
      { type: "song", durationSec: 60, instruction: "Strum any song you half-know with the folk pattern. It'll sound musical." },
    ],
    closingNote: "Rhythm is the first thing listeners hear. A clean chord in time sounds like music.",
  },
  {
    id: "g-t1-power-chords-chain",
    instrument: "guitar",
    phase: 1,
    name: "power chords",
    soulName: "The Rock Chug",
    minutes: 4,
    ghostKey: "E",
    pillar: "technique",
    steps: [
      { type: "triad", durationSec: 45, instruction: "Form E5 (low E + 2nd fret A). Two fingers. Slide the shape up." },
      { type: "progression", durationSec: 75, instruction: "E5→A5→D5→G5, two beats each at 80bpm. The shape never changes." },
      { type: "progression", durationSec: 60, instruction: "Move E5 up to F5, then up in half-steps to the 5th fret." },
      { type: "song", durationSec: 60, instruction: "Iron Man riff — it's E5/G5/A5/D5. Play it slow and heavy." },
    ],
    closingNote: "One moveable shape = the whole rock vocabulary. This is the electric guitar sound.",
    // V3 seed: micro-rest cadence + tempo ladder; eligible for interleaving.
    repBlocks: { repsPerBlock: 3, restSec: 12 },
    bpmLadder: { startBpm: 80, targetBpm: 120, step: 5, advanceAfterSuccesses: 3 },
    interleavable: true,
  },
  {
    id: "g-t1-palmmute-chain",
    instrument: "guitar",
    phase: 1,
    name: "palm muting",
    soulName: "Muted Crunch",
    minutes: 3,
    ghostKey: "E",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 45, instruction: "Rest the pick-hand heel on the strings at the bridge. Chunky, short sound." },
      { type: "tone", durationSec: 60, instruction: "2 bars muted E5, 2 bars open E5, at 80bpm. Audible contrast at each switch." },
      { type: "tone", durationSec: 30, instruction: "Lift slightly for open, settle back for muted. Control the on/off." },
      { type: "song", durationSec: 45, instruction: "Come As You Are — palm-muted throughout. Try the main riff muted." },
    ],
    closingNote: "Muting turns power chords from loud into rhythmic. The defining punk/metal texture.",
  },

  // ───── PHASE 2 — early intermediate ─────
  {
    id: "g-t2-legato-chain",
    instrument: "guitar",
    phase: 2,
    name: "hammer-ons & pull-offs",
    soulName: "Two Notes, One Pick",
    minutes: 4,
    ghostKey: "am",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 60, instruction: "G string 5h7 — pick fret 5, hammer to fret 7 with no second pick. Equal volume." },
      { type: "tone", durationSec: 60, instruction: "G string 7p5 — pick fret 7, pull off to 5 so it rings. 10 reps per string." },
      { type: "scale", durationSec: 60, instruction: "Combine: 5h7p5 across the strings. Smooth, even, legato." },
      { type: "song", durationSec: 60, instruction: "Sunshine of Your Love riff uses a hammer-on. Play it with the open-E drone." },
    ],
    closingNote: "Legato is how a solo flows instead of stutters. Equal volume is the goal.",
  },
  {
    id: "g-t2-bend-vibrato-chain",
    instrument: "guitar",
    phase: 2,
    name: "bends & vibrato",
    soulName: "Make a Note Cry",
    minutes: 4,
    ghostKey: "am",
    pillar: "expression",
    steps: [
      { type: "tone", durationSec: 75, instruction: "B string fret 7, bend up until it matches the pitch of fret 9. In tune, 8/10." },
      { type: "tone", durationSec: 60, instruction: "Add vibrato: fret 7, even oscillation, 4 wobbles per beat at 60bpm." },
      { type: "improv", durationSec: 60, instruction: "Bend, hold, add vibrato at the top. Let the note breathe and sing." },
      { type: "song", durationSec: 45, instruction: "Whole Lotta Love — Page's riff is pentatonic with blues bends. Try it." },
    ],
    closingNote: "The bend is the blues voice. A note that breathes beats a note that's just correct.",
  },
  {
    id: "g-t2-pentatonic-box1-chain",
    instrument: "guitar",
    phase: 2,
    name: "minor pentatonic: Box 1",
    soulName: "Your First Solo",
    minutes: 5,
    ghostKey: "am",
    pillar: "improv",
    steps: [
      { type: "scale", durationSec: 90, instruction: "Am pentatonic Box 1, ascending and descending at 100bpm. Alternate-picked." },
      { type: "scale", durationSec: 60, instruction: "Land on the root (A) at the start and end. Hear home." },
      { type: "improv", durationSec: 120, instruction: "Put on an Am backing track. Improvise for 2 minutes using only Box 1." },
      { type: "song", durationSec: 30, instruction: "Anything you play in this box over Am sounds like a solo. Prove it." },
    ],
    closingNote: "Your first improv vocabulary. Five notes, infinite phrases. You can solo now.",
  },
  {
    id: "g-t2-pentatonic-box2-chain",
    instrument: "guitar",
    phase: 2,
    name: "pentatonic: Box 2 + connect",
    soulName: "Move Up the Neck",
    minutes: 4,
    ghostKey: "am",
    pillar: "improv",
    steps: [
      { type: "scale", durationSec: 75, instruction: "Am pentatonic Box 2, ascending/descending at 80bpm." },
      { type: "scale", durationSec: 75, instruction: "Box 1 → Box 2 unbroken, then descend back. One smooth line." },
      { type: "improv", durationSec: 90, instruction: "Improvise over Am, moving between Box 1 and Box 2. Leave first position." },
      { type: "song", durationSec: 30, instruction: "A two-box solo covers more of the neck. Hear the range open up." },
    ],
    closingNote: "Connecting boxes is how you stop being stuck in one spot. The neck opens up.",
  },
  {
    id: "g-t2-barre-e-chain",
    instrument: "guitar",
    phase: 2,
    name: "barre chords: E shape",
    soulName: "The Shape That Moves",
    minutes: 4,
    ghostKey: "E",
    pillar: "technique",
    steps: [
      { type: "triad", durationSec: 75, instruction: "F major barre at fret 1 (E-shape). All six strings must ring." },
      { type: "progression", durationSec: 90, instruction: "Slide the E-shape: one-minute changes Bm↔F#m. Target 15+." },
      { type: "tone", durationSec: 30, instruction: "Roll the index slightly onto its side for a cleaner barre." },
      { type: "song", durationSec: 45, instruction: "Any song in F is now playable with one shape. Try a verse." },
    ],
    closingNote: "Every major and minor chord through one moveable shape. The fretboard just got smaller.",
  },
  {
    id: "g-t2-barre-a-chain",
    instrument: "guitar",
    phase: 2,
    name: "barre chords: A shape",
    soulName: "Any Key, Any Fret",
    minutes: 4,
    ghostKey: "A",
    pillar: "technique",
    steps: [
      { type: "triad", durationSec: 75, instruction: "B major barre at fret 2 (A-shape). Top five strings ring clean." },
      { type: "progression", durationSec: 90, instruction: "One-minute changes B↔E using E-shape and A-shape. Target 15+." },
      { type: "tone", durationSec: 30, instruction: "Combine shapes: any chord, anywhere, two ways to play it." },
      { type: "song", durationSec: 45, instruction: "A song that changes key is now no harder. Play one in any key." },
    ],
    closingNote: "Two barre shapes = any chord, any key, anywhere on the neck. Total freedom.",
  },

  // ───── PHASE 3 — intermediate rewards ─────
  {
    id: "g-t3-blues12-chain",
    instrument: "guitar",
    phase: 3,
    name: "12-bar blues",
    soulName: "The Spine of Rock",
    minutes: 6,
    ghostKey: "A",
    pillar: "repertoire",
    steps: [
      { type: "progression", durationSec: 120, instruction: "12-bar in A: A5 (4 bars), D5 (2), A5 (2), E5 (1), D5 (1), A5 (2). 75bpm." },
      { type: "tone", durationSec: 30, instruction: "Add a shuffle feel — long-short, long-short. The blues swing." },
      { type: "improv", durationSec: 120, instruction: "Loop the 12-bar, solo over it with Am pentatonic Box 1." },
      { type: "song", durationSec: 60, instruction: "You're now playing rhythm AND lead over a real form. La Grange is right here." },
    ],
    closingNote: "The harmonic spine of blues and rock. You can sit in with a band now.",
  },
  {
    id: "g-t3-phrasing-chain",
    instrument: "guitar",
    phase: 3,
    name: "lead phrasing: call & answer",
    soulName: "Ask and Answer",
    minutes: 5,
    ghostKey: "am",
    pillar: "expression",
    steps: [
      { type: "improv", durationSec: 90, instruction: "Play a 4-note phrase. Then one full bar of silence. Resist filling it." },
      { type: "improv", durationSec: 90, instruction: "Answer the phrase with another 4 notes — like a conversation." },
      { type: "improv", durationSec: 90, instruction: "Over a 12-bar loop: question, silence, answer, repeat. Breathe." },
      { type: "song", durationSec: 30, instruction: "The space is the music. A solo with rests sounds composed, not frantic." },
    ],
    closingNote: "Silence is part of the phrase. Q&A is what makes notes sound like a story.",
  },
  {
    id: "g-t3-licks-chain",
    instrument: "guitar",
    phase: 3,
    name: "pentatonic licks: Box 1",
    soulName: "Musical Sentences",
    minutes: 5,
    ghostKey: "am",
    pillar: "improv",
    steps: [
      { type: "scale", durationSec: 90, instruction: "Learn 3 classic Box 1 licks. Memorize each one cold." },
      { type: "scale", durationSec: 90, instruction: "Transpose each lick to 2 keys — move the box, the shape holds." },
      { type: "improv", durationSec: 90, instruction: "Drop your licks into an improv over Am. Connect them with bends." },
      { type: "song", durationSec: 30, instruction: "A vocabulary of licks is how real solos get built. You have one now." },
    ],
    closingNote: "Licks are sentences. Memorize a few, then start writing your own with them.",
  },
  {
    id: "g-t3-fullneck-chain",
    instrument: "guitar",
    phase: 3,
    name: "full-neck pentatonic",
    soulName: "The Whole Fretboard",
    minutes: 6,
    ghostKey: "am",
    pillar: "improv",
    steps: [
      { type: "scale", durationSec: 150, instruction: "The Pentatonic Highway: all 5 Am boxes, 5th fret up to the 17th and back." },
      { type: "scale", durationSec: 60, instruction: "Connect each box to the next with a slide. One unbroken line up the neck." },
      { type: "improv", durationSec: 120, instruction: "Improvise over Am moving freely between all five positions." },
      { type: "song", durationSec: 30, instruction: "The whole fretboard is one scale now. No more being stuck in a box." },
    ],
    closingNote: "Full fretboard freedom. The neck is no longer five separate rooms — it's one space.",
  },
  {
    id: "g-t3-syncopation-chain",
    instrument: "guitar",
    phase: 3,
    name: "syncopation & accents",
    soulName: "Rhythm With Attitude",
    minutes: 4,
    ghostKey: "em",
    pillar: "expression",
    steps: [
      { type: "progression", durationSec: 90, instruction: "D-x-DU-x-DU over Em at 90bpm. The 'x' is a muted percussive stroke." },
      { type: "tone", durationSec: 45, instruction: "Keep the muted strokes even — the groove lives in the silences." },
      { type: "progression", durationSec: 75, instruction: "Add accents on the off-beats. Push and pull against the click." },
      { type: "song", durationSec: 60, instruction: "Back in Black — alternating muted and open accents. That's the riff." },
    ],
    closingNote: "Syncopation is what makes a rhythm part feel alive instead of mechanical.",
  },

  // ───── Curriculum #8 — capo as a key multiplier ─────
  // The same One-Minute-Changes mechanism as open chords, but with a capo on:
  // clamp the capo, play known open shapes, and HEAR them sound in a new key.
  // The point is recognition (shape ≠ sounding key) + counting clean changes,
  // not new motor cost — that's the whole leverage of the capo.
  {
    id: "g-capo-chain",
    instrument: "guitar",
    phase: 1,
    name: "capo: shapes in a new key",
    soulName: "One Capo, Every Key",
    minutes: 4,
    ghostKey: "G",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 30, instruction: "Clamp the capo on fret 2, just behind the fret. Every string should ring clean — re-check tuning if it pulls sharp." },
      { type: "triad", durationSec: 45, instruction: "Play your G, C, D shapes with the capo on 2. The SHAPES are identical — but they now sound A, D, E. Same fingers, new key." },
      { type: "progression", durationSec: 90, instruction: "One-minute changes G↔C shapes WITH the capo on. Count clean changes — your open-chord fluency carries straight over." },
      { type: "song", durationSec: 45, instruction: "Find a song a step too high to sing — capo up two frets and play the open-chord version. It now sits in your range." },
    ],
    closingNote: "Five open shapes + one moving bar = every key, for near-zero new effort. The capo is the cheapest range you'll ever buy.",
  },

  // ───── Batch 3a — missing fundamentals ─────
  {
    id: "g-t1-amp-chain",
    instrument: "guitar",
    phase: 1,
    name: "amp and gain basics",
    soulName: "Clean or Mean",
    minutes: 9,
    ghostKey: "E",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 90,  instruction: "Find the gain knob and the volume knob on your amp or amp sim. Set gain low and volume about half, that is your home base." },
      { type: "tone", durationSec: 120, instruction: "Strum all six open strings at home base, then push gain past three-quarters and strum again. Name what changed." },
      { type: "tone", durationSec: 120, instruction: "Flip the pickup selector through every position while holding all six open strings ringing. Bridge is bright and cutting, neck is warm and round." },
      { type: "tone", durationSec: 120, instruction: "Rest your picking hand's edge on the low E and A strings at the bridge, strum them muted at home base, then at high gain. Notice which setting exposes a sloppy strum." },
      { type: "song", durationSec: 90,  instruction: "Enter Sandman opens clean then kicks into a driven riff. Copy the switch: strum clean, then flip to your driven setting." },
    ],
    closingNote: "Your practice tone just got honest. Home base for real work, big gain only when you have earned it.",
  },
  {
    id: "g-t2-fretboard-notes-chain",
    instrument: "guitar",
    phase: 2,
    name: "fretboard notes: low E and A strings",
    soulName: "Know Where You Are",
    minutes: 9,
    ghostKey: "G",
    pillar: "technique",
    steps: [
      { type: "tone", durationSec: 90,  instruction: "Touch the dot marker frets on the low E string, one at a time: fret 3 is G, fret 5 is A, fret 7 is B. Say each note out loud as you land on it." },
      { type: "tone", durationSec: 90,  instruction: "Now do the A string dots: fret 3 is C, fret 5 is D, fret 7 is E. Same three frets, three new letters." },
      { type: "tone", durationSec: 150, instruction: "Fill the gaps around the anchors. Low E string: open E, fret 1 F, fret 8 C, fret 10 D, fret 12 E. A string: open A, fret 2 B, fret 8 F, fret 10 G, fret 12 A." },
      { type: "tone", durationSec: 120, instruction: "Drill the octave shape from three different anchor frets: land on a note on the low E or A string, then move two strings up and two frets up and name the same note, now one octave up." },
      { type: "song", durationSec: 90,  instruction: "Play the Smoke on the Water riff and call out each note by name as you move through it, not just the fret numbers." },
    ],
    closingNote: "The low half of your neck just stopped being a blur of numbers. Every fret you slide to now has a name, and that name is exactly what barre chords, the capo, and picking the right power chord run on.",
  },
  {
    id: "g-t2-noise-control-chain",
    instrument: "guitar",
    phase: 2,
    name: "noise control under gain",
    soulName: "Kill the Squeal",
    minutes: 9,
    ghostKey: "am",
    pillar: "technique",
    steps: [
      { type: "tone",  durationSec: 90,  instruction: "Turn on some gain and fret one note high on the neck. Play it, then relax your whole hand and just listen to what the other strings do on their own." },
      { type: "tone",  durationSec: 120, instruction: "Rest the flat pad of your first finger lightly across the thinner strings above the one you are fretting, no pressing. Play the same note again and compare the quiet." },
      { type: "tone",  durationSec: 120, instruction: "Add the picking hand: rest the edge of your palm near the bridge across the thicker strings below your note. Hold both resting touches at once and play the note." },
      { type: "scale", durationSec: 150, instruction: "Play slowly up and down your Am pentatonic box, one note at a time, keeping both resting touches in place the entire way. Every note should snap out alone." },
      { type: "song",  durationSec: 60,  instruction: "Add a little more gain and play a short lick from a solo you love. Listen for total silence around every note, nothing ringing that you did not ask for." },
    ],
    closingNote: "Your notes now ring alone under gain, nothing extra buzzing behind them. That is the difference between a clean solo and a mess.",
  },
  {
    id: "g-t2-mini-barre-chain",
    instrument: "guitar",
    phase: 2,
    name: "Fmaj7 to the small F",
    soulName: "Two Strings, First Barre",
    minutes: 5,
    ghostKey: "C",
    pillar: "technique",
    steps: [
      { type: "triad",       durationSec: 60, instruction: "Form Fmaj7: mute low E and A, third finger D string third fret, second finger G string second fret, first finger B string first fret, high E open. Strum and let it ring." },
      { type: "tone",        durationSec: 45, instruction: "Sit with Fmaj7 for a few slow strums. Notice it already sounds like a finished chord, not a half built one." },
      { type: "triad",       durationSec: 60, instruction: "Roll the first finger flat so it covers both the B string and the high E string at fret one. That is the small F, your first real barre. Check both strings ring." },
      { type: "progression", durationSec: 90, instruction: "Roll between Fmaj7 and the small F, slow and steady, ten times. Every high E string should ring clean on the small F, never buzz or go dead." },
      { type: "song",        durationSec: 45, instruction: "Strum through the C, G, Am, F progression from Let It Be, using the small F for the F chord. Hear your first barre in a real song." },
    ],
    closingNote: "Your first finger just learned to lie flat and hold two strings at once. That is the exact motor skill the full six string barre needs next.",
  },

  // ───── Batch 3b — breadth (blues note, bend types, driving rhythm) ─────
  {
    id: "g-t2-blues-note-chain",
    instrument: "guitar",
    phase: 2,
    name: "the blues note",
    soulName: "The Blue Note",
    minutes: 6,
    ghostKey: "am",
    pillar: "improv",
    steps: [
      { type: "scale", durationSec: 60,  instruction: "Run Am pentatonic Box 1 up and down once to warm the shape, alternate-picked. This is the box you already own, five notes." },
      { type: "tone",  durationSec: 75,  instruction: "Find the blues note: the A string, sixth fret. It sits right between the D at the fifth fret and the E at the seventh. Pick it on its own and hear how tense and unresolved it is." },
      { type: "tone",  durationSec: 90,  instruction: "Slink through it: slide from the fifth fret up into the blues note at the sixth, then push on up to the E at the seventh. Slow and greasy. Never park on the blues note, always move off it." },
      { type: "improv", durationSec: 120, instruction: "Put on an Am groove and improvise using Box 1, but pass through the blues note on the way between the D and the E. One note, and your solo just went from clean to bluesy." },
      { type: "song",  durationSec: 45,  instruction: "That tense passing note is the whole flavour of blues-rock lead. Aim for it, slide off it, and you sound like the record." },
    ],
    closingNote: "One extra note turned your pentatonic box into the blues scale. The blues note is the single highest-value note in rock and blues lead, and now it is in your hands.",
  },
  {
    id: "g-t2-bend-half-chain",
    instrument: "guitar",
    phase: 2,
    name: "half-step, unison and held bends",
    soulName: "Bends That Sit In Tune",
    minutes: 6,
    ghostKey: "am",
    pillar: "expression",
    steps: [
      { type: "tone",  durationSec: 75,  instruction: "Half-step bend: B string, seventh fret. Bend up only until it matches the pitch of the eighth fret, one fret's worth. This small bend is the everyday one, and stopping it in tune is the whole skill." },
      { type: "tone",  durationSec: 60,  instruction: "Held bend: bend the B string at the seventh fret up a whole step to the ninth fret's pitch, then hold it dead steady while it rings, no drooping. Support the bend with two or three fingers together." },
      { type: "tone",  durationSec: 90,  instruction: "Unison bend: hold the B string at the fifth fret and let it ring. Now bend the G string at the seventh fret up a whole step until it matches that exact pitch, two strings crying as one." },
      { type: "improv", durationSec: 75,  instruction: "Over an Am groove, work all three into a phrase: a half-step bend for tension, a held bend that sits and sings, a unison bend for a thick vocal cry." },
      { type: "song",  durationSec: 30,  instruction: "Check every bend against a fresh fretted note. In tune or it is worse than no bend at all." },
    ],
    closingNote: "Whole-step bends were step one. Half-step, held, and unison bends are what actually fill real solos, and now every one of them can land in tune.",
  },
  {
    id: "g-t1-drive-chain",
    instrument: "guitar",
    phase: 1,
    name: "driving rhythm: down-picked eighths and gallop",
    soulName: "The Rock Engine",
    minutes: 6,
    ghostKey: "E",
    pillar: "technique",
    steps: [
      { type: "tone",  durationSec: 75,  instruction: "Down-picked straight eighth notes on E5, every stroke a downstroke, at 90bpm. Count one-and-two-and. Keep the wrist loose so it does not tire, and keep every hit exactly the same volume." },
      { type: "tone",  durationSec: 60,  instruction: "Hold the drive for a full minute without slowing or getting choppy. This is a stamina skill, that steady down-picked wall is the whole engine of punk and metal rhythm." },
      { type: "tone",  durationSec: 75,  instruction: "The gallop: palm-mute the strings and pick one long note then two quick ones per beat, da, da-da. Keep it tight and even. That chugging horse-hooves feel is the gallop." },
      { type: "progression", durationSec: 90, instruction: "Drive E5, then G5, then A5, two beats each, alternating a bar of straight down-picked eighths with a bar of the muted gallop. Switch cleanly between the two feels." },
      { type: "song",  durationSec: 60,  instruction: "Blitzkrieg Bop runs on pure down-picked eighth-note power chords. Play it at a comfortable tempo and just do not stop, let the drive carry you." },
    ],
    closingNote: "You now have the rock engine: a relentless down-picked wall and a tight palm-muted gallop. This is the rhythm feel under most of the rock, punk, and metal you love.",
  },

  // ───── Curriculum #2 — timed chord-transition fluency ─────
  // A TRANSITION drill (transitionPairId set): the slot renders the 60-second
  // clean-change counter. Clearing ~30/min marks g-trans-G-C learned, gating the
  // 12-Bar Blues "jam-ready" unlock.
  {
    id: "g-trans-G-C-drill",
    instrument: "guitar",
    phase: 1,
    name: "G → C, one-minute changes",
    soulName: "The Last Reps Before the Song",
    minutes: 2,
    ghostKey: "G",
    pillar: "technique",
    transitionPairId: "G-C",
    steps: [
      { type: "progression", durationSec: 60, instruction: "Switch G↔C cleanly for 60 seconds. Count each clean change. Target 30." },
    ],
    closingNote: "The hardest open-chord change. The count going up is the whole game.",
  },
];

export const GUITAR_CHAIN_DRILLS: ChainDrill[] = withDefaultMotorConfigAll(RAW_GUITAR_CHAIN_DRILLS);
