// Guitar skill-tree DAG — GUITAR_NODES.
//
// The 26 nodes from plan §2.4 (Report 2 Part 2), carried over VERBATIM: ids,
// tiers, prereqs, masteryDrill, unlock, viz, chordShape, cagedShape all match the
// plan exactly. Added per Phase-4 scope:
//   - instrument: "guitar" on every node.
//   - chainDrillId on nodes a chain drill should satisfy (ids match lib/guitar/chainDrills.ts).
//   - unlockCardId on nodes that should fire an unlock celebration (ids match lib/guitar/unlocks.ts).
//
// endSession marks a node `learned` when its linked chainDrillId is played (or its
// keyId reaches depth >=2) AND its full prereq chain is already learned — so the
// unlock celebration cannot fire out of order. Every unlockCardId here resolves to
// a real UnlockCard, and no two nodes share a card (data-integrity test enforces both).
//
// Tiers (sunrise ramp, shared with piano):
//   t0 setup/orientation · t1 beginner foundations · t2 early intermediate ·
//   t3 intermediate rewards.

import type { SkillNode } from "../types";

export const GUITAR_NODES: SkillNode[] = [
  // ───── Tier 0 — setup & orientation ─────
  {
    id: "g-t0-anatomy",
    instrument: "guitar",
    title: "Guitar Anatomy & Tuning",
    tier: 0,
    category: "setup",
    prereqs: [],
    masteryDrill: "Name all 6 open strings, tune from scratch <90s",
    unlock: "Tune & orient independently",
    chainDrillId: "g-t0-tuning-chain",
    unlockCardId: "u-g-anatomy",
  },
  {
    id: "g-t0-posture",
    instrument: "guitar",
    title: "Holding & Pick Grip",
    tier: 0,
    category: "technique",
    prereqs: ["g-t0-anatomy"],
    masteryDrill: "30s body check: wrist relaxed, thumb behind neck, pick 45°",
    unlock: "Foundation posture",
    viz: "animation",
  },
  {
    id: "g-t0-tab",
    instrument: "guitar",
    title: "Reading Tab Basics",
    tier: 0,
    category: "notation",
    prereqs: ["g-t0-anatomy"],
    masteryDrill: "Read Seven Nation Army tab by fret-number, no playing",
    unlock: "Decode any basic tab",
    viz: "tab",
    chainDrillId: "g-t0-tab-chain",
    unlockCardId: "u-g-tab",
  },

  // ───── Tier 1 — beginner foundations ─────
  {
    id: "g-t1-fretting",
    instrument: "guitar",
    title: "Fretting Hand Placement",
    tier: 1,
    category: "technique",
    prereqs: ["g-t0-posture"],
    masteryDrill: "Every string rings clean frets 1-5, fingertip only",
    unlock: "Clean single-note fretting",
    chainDrillId: "g-t1-fretting-chain",
  },
  {
    id: "g-t1-downpick",
    instrument: "guitar",
    title: "Down-Picking",
    tier: 1,
    category: "technique",
    prereqs: ["g-t0-posture"],
    masteryDrill: "Open-E downstrokes 60bpm 1min, even volume",
    unlock: "Controlled attack",
    chainDrillId: "g-t1-downpick-chain",
    unlockCardId: "u-g-first-riff",
  },
  {
    id: "g-t1-altpick",
    instrument: "guitar",
    title: "Alternate Picking",
    tier: 1,
    category: "technique",
    prereqs: ["g-t1-downpick"],
    masteryDrill: "Chromatic 1-2-3-4 all 6 strings, alt-pick 80bpm",
    unlock: "Efficient scale motion",
    chainDrillId: "g-t1-altpick-chain",
  },
  {
    id: "g-t1-openEM",
    instrument: "guitar",
    title: "Open Chords — Em, Am, E, A",
    tier: 1,
    category: "chords",
    prereqs: ["g-t1-fretting", "g-t1-downpick"],
    masteryDrill: "1-min changes Em↔Am ≥30; E↔A ≥30, all strings ring",
    unlock: "Play dozens of songs in E/A minor",
    viz: "chord_diagram",
    chordShape: [0, 2, 2, 0, 0, 0] /*Em*/,
    chainDrillId: "g-t1-open-chords-em-chain",
    unlockCardId: "u-g-open-chords",
    fluencyTest: { prompt: "Switch Em↔Am↔E↔A in time with a backing track, eyes on the page (not your fretting hand)." },
  },
  {
    id: "g-t1-openDGC",
    instrument: "guitar",
    title: "Open Chords — D, G, C",
    tier: 1,
    category: "chords",
    prereqs: ["g-t1-openEM"],
    masteryDrill: "1-min changes G↔C ≥30; D↔G ≥30",
    unlock: "Full open-chord vocabulary",
    viz: "chord_diagram",
    chordShape: [-1, 3, 2, 0, 1, 0] /*C*/,
    chainDrillId: "g-t1-open-chords-dgc-chain",
    unlockCardId: "u-g-open-chords-full",
  },
  {
    id: "g-t1-strum",
    instrument: "guitar",
    title: "Basic Strumming",
    tier: 1,
    category: "rhythm",
    prereqs: ["g-t1-openEM", "g-t1-downpick"],
    masteryDrill: "D-DU-UDU over Em→Am→C→G 80bpm 2min",
    unlock: "Accompany songs",
    chainDrillId: "g-t1-strum-chain",
  },
  {
    id: "g-t1-power",
    instrument: "guitar",
    title: "Power Chords",
    tier: 1,
    category: "chords",
    prereqs: ["g-t1-fretting", "g-t1-downpick"],
    masteryDrill: "E5→A5→D5→G5 2 beats each 80bpm, moveable",
    unlock: "Rock rhythm — entire rock/punk/metal vocabulary",
    viz: "chord_diagram",
    chordShape: [0, 2, 2, -1, -1, -1] /*E5*/,
    chainDrillId: "g-t1-power-chords-chain",
    unlockCardId: "u-g-power-chords",
    fluencyTest: { prompt: "Play the E5→A5→D5→G5 riff to a backing track without looking at the fretboard." },
  },
  {
    id: "g-t1-palmmute",
    instrument: "guitar",
    title: "Palm Muting",
    tier: 1,
    category: "technique",
    prereqs: ["g-t1-power"],
    masteryDrill: "2 bars muted E5 / 2 bars open E5 80bpm, audible contrast",
    unlock: "Rhythmic punch",
    viz: "animation",
    chainDrillId: "g-t1-palmmute-chain",
  },
  {
    id: "g-t1-tabrhythm",
    instrument: "guitar",
    title: "Tab Rhythm Reading",
    tier: 1,
    category: "notation",
    prereqs: ["g-t0-tab"],
    masteryDrill: "Tap a 4-bar tab rhythm before playing, note values correct",
    unlock: "Learn from tab without hearing",
    viz: "tab",
  },

  // ───── Tier 2 — early intermediate ─────
  {
    id: "g-t2-hammer",
    instrument: "guitar",
    title: "Hammer-Ons",
    tier: 2,
    category: "technique",
    prereqs: ["g-t1-fretting", "g-t1-altpick"],
    masteryDrill: "G string 5h7 equal volume, 10 reps/string",
    unlock: "Legato phrasing",
    viz: "tab",
    chainDrillId: "g-t2-legato-chain",
  },
  {
    id: "g-t2-pulloff",
    instrument: "guitar",
    title: "Pull-Offs",
    tier: 2,
    category: "technique",
    prereqs: ["g-t2-hammer"],
    masteryDrill: "G string 7p5 rings clearly, 10 reps/string",
    unlock: "Full legato vocabulary",
    viz: "tab",
  },
  {
    id: "g-t2-slide",
    instrument: "guitar",
    title: "Slides",
    tier: 2,
    category: "technique",
    prereqs: ["g-t1-fretting", "g-t1-altpick"],
    masteryDrill: "B string 5/7 and 7\\5 80bpm, landing rings full beat",
    unlock: "Melodic glide",
    viz: "tab",
  },
  {
    id: "g-t2-bend",
    instrument: "guitar",
    title: "String Bending — Whole Step",
    tier: 2,
    category: "technique",
    prereqs: ["g-t2-hammer", "g-t2-slide"],
    masteryDrill: "B fret7→sound of fret9, in-tune 8/10 vs reference",
    unlock: "The blues voice",
    viz: "animation",
    chainDrillId: "g-t2-bend-vibrato-chain",
    unlockCardId: "u-g-bend",
  },
  {
    id: "g-t2-vibrato",
    instrument: "guitar",
    title: "Vibrato",
    tier: 2,
    category: "technique",
    prereqs: ["g-t2-bend"],
    masteryDrill: "B fret7 even oscillation 4×/beat 60bpm 8s",
    unlock: "Sustained notes breathe",
    viz: "animation",
  },
  {
    id: "g-t2-pent-box1",
    instrument: "guitar",
    title: "Minor Pentatonic — Box 1",
    tier: 2,
    category: "scales",
    prereqs: ["g-t1-altpick", "g-t2-hammer", "g-t2-slide"],
    masteryDrill: "Am Box1 100bpm; improvise over Am track 2min",
    unlock: "First improv vocabulary — solo over rock/blues",
    viz: "fretboard_map",
    chainDrillId: "g-t2-pentatonic-box1-chain",
    unlockCardId: "u-g-pentatonic",
    fluencyTest: { prompt: "Improvise over an Am backing track using Box 1 while keeping a steady tap with your foot." },
  },
  {
    id: "g-t2-pent-box2",
    instrument: "guitar",
    title: "Minor Pentatonic — Box 2 + Connect",
    tier: 2,
    category: "scales",
    prereqs: ["g-t2-pent-box1"],
    masteryDrill: "Box1→Box2 unbroken 80bpm, descend back",
    unlock: "Leave first position",
    viz: "fretboard_map",
    chainDrillId: "g-t2-pentatonic-box2-chain",
  },
  {
    id: "g-t2-barre-E",
    instrument: "guitar",
    title: "Barre Chords — E Shape",
    tier: 2,
    category: "chords",
    prereqs: ["g-t1-openEM", "g-t1-power"],
    masteryDrill: "F barre fret1 all 6 ring; 1-min Bm↔F#m ≥15",
    unlock: "Every major/minor chord via one shape",
    viz: "chord_diagram",
    cagedShape: "E",
    chainDrillId: "g-t2-barre-e-chain",
    unlockCardId: "u-g-barre",
  },
  {
    id: "g-t2-barre-A",
    instrument: "guitar",
    title: "Barre Chords — A Shape",
    tier: 2,
    category: "chords",
    prereqs: ["g-t1-openDGC", "g-t2-barre-E"],
    masteryDrill: "B barre fret2; 1-min B↔E ≥15",
    unlock: "Any key anywhere",
    viz: "chord_diagram",
    cagedShape: "A",
    chainDrillId: "g-t2-barre-a-chain",
  },

  // ───── Tier 3 — intermediate rewards ─────
  {
    id: "g-t3-blues12",
    instrument: "guitar",
    title: "12-Bar Blues",
    tier: 3,
    category: "repertoire",
    prereqs: ["g-t1-power", "g-t1-strum", "g-t2-pent-box1"],
    masteryDrill: "12-bar in A power chords 75bpm, then solo Box1",
    unlock: "Harmonic spine of blues/rock; can jam",
    chainDrillId: "g-t3-blues12-chain",
    unlockCardId: "u-g-blues12",
  },
  {
    id: "g-t3-phrasing",
    instrument: "guitar",
    title: "Lead Phrasing — Q&A",
    tier: 3,
    category: "expression",
    prereqs: ["g-t2-pent-box1", "g-t2-vibrato"],
    masteryDrill: "4-note phrase, 1 bar silence, 4-note answer over 12-bar",
    unlock: "Solos sound musical",
    chainDrillId: "g-t3-phrasing-chain",
    unlockCardId: "u-g-phrasing",
  },
  {
    id: "g-t3-licks",
    instrument: "guitar",
    title: "Pentatonic Licks — Box 1",
    tier: 3,
    category: "scales",
    prereqs: ["g-t2-pent-box1", "g-t2-bend", "g-t2-vibrato"],
    masteryDrill: "3 memorized licks, transposed to 2 keys each",
    unlock: "Solo with intent",
    viz: "tab",
    chainDrillId: "g-t3-licks-chain",
  },
  {
    id: "g-t3-fullneck",
    instrument: "guitar",
    title: "Full-Neck Pentatonic",
    tier: 3,
    category: "scales",
    prereqs: ["g-t2-pent-box2"],
    masteryDrill: "Pentatonic Highway: 5 boxes 5th→17th fret and back",
    unlock: "Full fretboard freedom",
    viz: "fretboard_map",
    chainDrillId: "g-t3-fullneck-chain",
  },
  {
    id: "g-t3-bendaccuracy",
    instrument: "guitar",
    title: "Bending Accuracy + Expression",
    tier: 3,
    category: "technique",
    prereqs: ["g-t2-bend", "g-t2-vibrato"],
    masteryDrill: "Whole-step bends in-tune 9/10; pre-bend",
    unlock: "Real blues-rock lead",
    viz: "animation",
  },
  {
    id: "g-t3-syncopation",
    instrument: "guitar",
    title: "Rhythm Syncopation & Accents",
    tier: 3,
    category: "rhythm",
    prereqs: ["g-t1-strum", "g-t1-palmmute"],
    masteryDrill: "D-x-DU-x-DU over Em 90bpm 2min, muted strokes even",
    unlock: "Rhythm sounds alive",
    chainDrillId: "g-t3-syncopation-chain",
  },
];
