// Guitar skill-tree DAG — GUITAR_NODES.
//
// The 26 nodes from plan §2.4 (Report 2 Part 2), carried over VERBATIM: ids,
// tiers, prereqs, masteryDrill, unlock, viz, chordShape, cagedShape all match the
// plan exactly. Added per Phase-4 scope:
//   - instrument: "guitar" on every node.
//   - chainDrillId on nodes a chain drill should satisfy (ids match lib/guitar/chainDrills.ts).
//   - unlockCardId on nodes that should fire an unlock celebration (ids match lib/guitar/unlocks.ts).
//
// endSession marks a node `learned` when its linked chainDrillId is played (or its
// keyId reaches depth >=2) AND its full prereq chain is already learned — so the
// unlock celebration cannot fire out of order. Every unlockCardId here resolves to
// a real UnlockCard, and no two nodes share a card (data-integrity test enforces both).
//
// Tiers (sunrise ramp, shared with piano):
//   t0 setup/orientation · t1 beginner foundations · t2 early intermediate ·
//   t3 intermediate rewards.

import type { SkillNode } from "../types";

// V4 soul-first labels + path membership applied per docs/research/soul-first-learning.md
// Section 3 (guitar table). Path-tag rule: rhythm/chord/foundation skills are on all
// three paths; lead/expression skills are play-with-soul + go-deep; theory nodes are
// go-deep + theory:true and carry NO soulTitle (they only show in Go Deep, where the
// theory name is the right label). All fields optional and backward-compatible.

export const GUITAR_NODES: SkillNode[] = [
  // ───── Tier 0 — setup & orientation ─────
  {
    id: "g-t0-anatomy",
    instrument: "guitar",
    title: "Guitar Anatomy & Tuning",
    tier: 0,
    category: "setup",
    prereqs: [],
    masteryDrill: "Name all 6 open strings, tune from scratch <90s",
    unlock: "Tune & orient independently",
    chainDrillId: "g-t0-tuning-chain",
    unlockCardId: "u-g-anatomy",
    soulTitle: "Your Guitar's Names",
    keepTitle: "Guitar Anatomy & Tuning",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t0-posture",
    instrument: "guitar",
    title: "Holding & Pick Grip",
    tier: 0,
    category: "technique",
    prereqs: ["g-t0-anatomy"],
    masteryDrill: "30s body check: wrist relaxed, thumb behind neck, pick 45°",
    unlock: "Foundation posture",
    viz: "animation",
    soulTitle: "Hold It Right",
    keepTitle: "Holding & Pick Grip",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t0-tab",
    instrument: "guitar",
    title: "Reading Tab Basics",
    tier: 0,
    category: "notation",
    prereqs: ["g-t0-anatomy"],
    masteryDrill: "Read Seven Nation Army tab by fret-number, no playing",
    unlock: "Decode any basic tab",
    viz: "tab",
    chainDrillId: "g-t0-tab-chain",
    unlockCardId: "u-g-tab",
    soulTitle: "Read the Map",
    keepTitle: "Reading Tab Basics",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },

  // ───── Tier 1 — beginner foundations ─────
  {
    id: "g-t1-fretting",
    instrument: "guitar",
    title: "Fretting Hand Placement",
    tier: 1,
    category: "technique",
    prereqs: ["g-t0-posture"],
    masteryDrill: "Every string rings clean frets 1-5, fingertip only",
    unlock: "Clean single-note fretting",
    chainDrillId: "g-t1-fretting-chain",
    soulTitle: "Clean Notes",
    keepTitle: "Fretting Hand Placement",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t1-downpick",
    instrument: "guitar",
    title: "Down-Picking",
    tier: 1,
    category: "technique",
    prereqs: ["g-t0-posture"],
    masteryDrill: "Open-E downstrokes 60bpm 1min, even volume",
    unlock: "Controlled attack",
    chainDrillId: "g-t1-downpick-chain",
    unlockCardId: "u-g-first-riff",
    soulTitle: "Hit It Once",
    keepTitle: "Down-Picking",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t1-altpick",
    instrument: "guitar",
    title: "Alternate Picking",
    tier: 1,
    category: "technique",
    prereqs: ["g-t1-downpick"],
    masteryDrill: "Chromatic 1-2-3-4 all 6 strings, alt-pick 80bpm",
    unlock: "Efficient scale motion",
    chainDrillId: "g-t1-altpick-chain",
    soulTitle: "Pick in Both Directions",
    keepTitle: "Alternate Picking",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t1-openEM",
    instrument: "guitar",
    title: "Open Chords — Em, Am, E, A",
    tier: 1,
    category: "chords",
    prereqs: ["g-t1-fretting", "g-t1-downpick"],
    masteryDrill: "1-min changes Em↔Am ≥30; E↔A ≥30, all strings ring",
    unlock: "Play dozens of songs in E/A minor",
    viz: "chord_diagram",
    chordShape: [0, 2, 2, 0, 0, 0] /*Em*/,
    chainDrillId: "g-t1-open-chords-em-chain",
    unlockCardId: "u-g-open-chords",
    fluencyTest: { prompt: "Switch Em↔Am↔E↔A in time with a backing track, eyes on the page (not your fretting hand)." },
    soulTitle: "The Minor Heart",
    keepTitle: "Open Chords (Em, Am, E, A)",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t1-openDGC",
    instrument: "guitar",
    title: "Open Chords — D, G, C",
    tier: 1,
    category: "chords",
    prereqs: ["g-t1-openEM"],
    masteryDrill: "1-min changes G↔C ≥30; D↔G ≥30",
    unlock: "Full open-chord vocabulary",
    viz: "chord_diagram",
    chordShape: [-1, 3, 2, 0, 1, 0] /*C*/,
    chainDrillId: "g-t1-open-chords-dgc-chain",
    unlockCardId: "u-g-open-chords-full",
    soulTitle: "The Full Chord Set",
    keepTitle: "Open Chords (D, G, C)",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t1-capo",
    instrument: "guitar",
    title: "The Capo — One Shape, Every Key",
    tier: 1,
    category: "chords",
    // After BOTH open-chord sets: the capo's whole value is reusing shapes you
    // already own. With the full open vocabulary, one moving bar unlocks every key.
    prereqs: ["g-t1-openEM", "g-t1-openDGC"],
    masteryDrill: "Capo on 2: play G/C/D shapes, name the sounding key (A/D/E). 1-min changes G↔C with the capo on.",
    unlock: "Play in any key with the 5 open shapes you already know — the capo multiplies a small vocabulary across the whole spectrum.",
    viz: "chord_diagram",
    chordShape: [-1, 3, 2, 0, 1, 0] /*C shape — the chart's first row*/,
    chainDrillId: "g-capo-chain",
    soulTitle: "One Capo, Every Key",
    keepTitle: "The Capo (Key Multiplier)",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t1-strum",
    instrument: "guitar",
    title: "Basic Strumming",
    tier: 1,
    category: "rhythm",
    prereqs: ["g-t1-openEM", "g-t1-downpick"],
    masteryDrill: "D-DU-UDU over Em→Am→C→G 80bpm 2min",
    unlock: "Accompany songs",
    chainDrillId: "g-t1-strum-chain",
    soulTitle: "The Strum Pattern",
    keepTitle: "Basic Strumming",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t1-power",
    instrument: "guitar",
    title: "Power Chords",
    tier: 1,
    category: "chords",
    prereqs: ["g-t1-fretting", "g-t1-downpick"],
    masteryDrill: "E5→A5→D5→G5 2 beats each 80bpm, moveable",
    unlock: "Rock rhythm — entire rock/punk/metal vocabulary",
    viz: "chord_diagram",
    chordShape: [0, 2, 2, -1, -1, -1] /*E5*/,
    chainDrillId: "g-t1-power-chords-chain",
    unlockCardId: "u-g-power-chords",
    fluencyTest: { prompt: "Play the E5→A5→D5→G5 riff to a backing track without looking at the fretboard." },
    soulTitle: "The Rock Chug",
    keepTitle: "Power Chords",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t1-palmmute",
    instrument: "guitar",
    title: "Palm Muting",
    tier: 1,
    category: "technique",
    prereqs: ["g-t1-power"],
    masteryDrill: "2 bars muted E5 / 2 bars open E5 80bpm, audible contrast",
    unlock: "Rhythmic punch",
    viz: "animation",
    chainDrillId: "g-t1-palmmute-chain",
    soulTitle: "Muted Crunch",
    keepTitle: "Palm Muting",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t1-tabrhythm",
    instrument: "guitar",
    title: "Tab Rhythm Reading",
    tier: 1,
    category: "notation",
    prereqs: ["g-t0-tab"],
    masteryDrill: "Tap a 4-bar tab rhythm before playing, note values correct",
    unlock: "Learn from tab without hearing",
    viz: "tab",
    keepTitle: "Tab Rhythm Reading",
    pathTags: ["go-deep"],
    theory: true,
  },
  {
    id: "g-t1-amp",
    instrument: "guitar",
    title: "Amp & Gain Basics",
    tier: 1,
    category: "setup",
    // Batch 3a — zero amp/gain content existed despite being tested from Grade 3-4.
    // Not a hard prereq of power/palm-mute (those are learnable unplugged); the
    // pedagogical tie lives in the lesson prose. pathTags omitted = every path.
    prereqs: ["g-t0-posture", "g-t0-anatomy"],
    masteryDrill: "Dial gain low and volume moderate for home base, then push gain past three-quarters and name what changed.",
    unlock: "Can set an honest practice tone from cold and explain what gain, volume, and the pickup selector each do to the sound.",
    viz: "animation",
    chainDrillId: "g-t1-amp-chain",
    soulTitle: "Clean or Mean",
    keepTitle: "Amp & Gain Basics",
  },

  // ───── Tier 2 — early intermediate ─────
  {
    id: "g-t2-hammer",
    instrument: "guitar",
    title: "Hammer-Ons",
    tier: 2,
    category: "technique",
    prereqs: ["g-t1-fretting", "g-t1-altpick"],
    masteryDrill: "G string 5h7 equal volume, 10 reps/string",
    unlock: "Legato phrasing",
    viz: "tab",
    chainDrillId: "g-t2-legato-chain",
    soulTitle: "One Pick, Two Notes",
    keepTitle: "Hammer-Ons",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t2-pulloff",
    instrument: "guitar",
    title: "Pull-Offs",
    tier: 2,
    category: "technique",
    prereqs: ["g-t2-hammer"],
    masteryDrill: "G string 7p5 rings clearly, 10 reps/string",
    unlock: "Full legato vocabulary",
    viz: "tab",
    soulTitle: "Pull Back Into Sound",
    keepTitle: "Pull-Offs",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t2-slide",
    instrument: "guitar",
    title: "Slides",
    tier: 2,
    category: "technique",
    prereqs: ["g-t1-fretting", "g-t1-altpick"],
    masteryDrill: "B string 5/7 and 7\\5 80bpm, landing rings full beat",
    unlock: "Melodic glide",
    viz: "tab",
    soulTitle: "Glide Between Notes",
    keepTitle: "Slides",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t2-bend",
    instrument: "guitar",
    title: "String Bending — Whole Step",
    tier: 2,
    category: "technique",
    prereqs: ["g-t2-hammer", "g-t2-slide"],
    masteryDrill: "B fret7→sound of fret9, in-tune 8/10 vs reference",
    unlock: "The blues voice",
    viz: "animation",
    chainDrillId: "g-t2-bend-vibrato-chain",
    unlockCardId: "u-g-bend",
    soulTitle: "Make a Note Cry",
    keepTitle: "String Bending (Whole Step)",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t2-vibrato",
    instrument: "guitar",
    title: "Vibrato",
    tier: 2,
    category: "technique",
    prereqs: ["g-t2-bend"],
    masteryDrill: "B fret7 even oscillation 4×/beat 60bpm 8s",
    unlock: "Sustained notes breathe",
    viz: "animation",
    soulTitle: "Make a Note Breathe",
    keepTitle: "Vibrato",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t2-pent-box1",
    instrument: "guitar",
    title: "Minor Pentatonic — Box 1",
    tier: 2,
    category: "scales",
    prereqs: ["g-t1-altpick", "g-t2-hammer", "g-t2-slide"],
    masteryDrill: "Am Box1 100bpm; improvise over Am track 2min",
    unlock: "First improv vocabulary — solo over rock/blues",
    viz: "fretboard_map",
    chainDrillId: "g-t2-pentatonic-box1-chain",
    unlockCardId: "u-g-pentatonic",
    fluencyTest: { prompt: "Improvise over an Am backing track using Box 1 while keeping a steady tap with your foot." },
    soulTitle: "Your First Solo",
    keepTitle: "Minor Pentatonic (Box 1)",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t2-pent-box2",
    instrument: "guitar",
    title: "Minor Pentatonic — Box 2 + Connect",
    tier: 2,
    category: "scales",
    prereqs: ["g-t2-pent-box1"],
    masteryDrill: "Box1→Box2 unbroken 80bpm, descend back",
    unlock: "Leave first position",
    viz: "fretboard_map",
    chainDrillId: "g-t2-pentatonic-box2-chain",
    soulTitle: "Move Up the Neck",
    keepTitle: "Minor Pentatonic (Box 2 + Connect)",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t2-barre-E",
    instrument: "guitar",
    title: "Barre Chords — E Shape",
    tier: 2,
    category: "chords",
    // Batch 3a: +g-t2-fretboard-notes (the barre lesson names F/G roots it never
    // taught) and +g-t2-mini-barre (the two-string scaffold before the full six),
    // so the single most common quit point stops being a one-step cliff.
    prereqs: ["g-t1-openEM", "g-t1-power", "g-t2-fretboard-notes", "g-t2-mini-barre"],
    masteryDrill: "F barre fret1 all 6 ring; 1-min Bm↔F#m ≥15",
    unlock: "Every major/minor chord via one shape",
    viz: "chord_diagram",
    cagedShape: "E",
    chainDrillId: "g-t2-barre-e-chain",
    unlockCardId: "u-g-barre",
    soulTitle: "The Shape That Moves",
    keepTitle: "Barre Chords (E Shape)",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t2-barre-A",
    instrument: "guitar",
    title: "Barre Chords — A Shape",
    tier: 2,
    category: "chords",
    prereqs: ["g-t1-openDGC", "g-t2-barre-E"],
    masteryDrill: "B barre fret2; 1-min B↔E ≥15",
    unlock: "Any key anywhere",
    viz: "chord_diagram",
    cagedShape: "A",
    chainDrillId: "g-t2-barre-a-chain",
    soulTitle: "Any Key, Any Fret",
    keepTitle: "Barre Chords (A Shape)",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
  {
    id: "g-t2-fretboard-notes",
    instrument: "guitar",
    title: "Fretboard Note Names (Low E and A Strings)",
    tier: 2,
    category: "notation",
    // Batch 3a — power chords, barre chords, and the capo all secretly rely on
    // knowing which note sits at which fret. Feeds g-t2-barre-E. category notation
    // (teaches a map, no new physical motion). pathTags omitted = every path.
    prereqs: ["g-t1-power"],
    masteryDrill: "Name any fret 0 to 12 on the low E and A strings, both directions, 10 for 10.",
    unlock: "Can name any natural note on the low E and A strings on sight, and find its octave using the octave shape.",
    viz: "fretboard_map",
    chainDrillId: "g-t2-fretboard-notes-chain",
    fluencyTest: { prompt: "With no visual fretboard reference, call out the note at five random frets on the low E string and five on the A string, under three seconds each, eight of ten correct." },
    soulTitle: "Know Where You Are",
    keepTitle: "Fretboard Note Names (Low E and A Strings)",
  },
  {
    id: "g-t2-noise-control",
    instrument: "guitar",
    title: "Noise Control Under Gain",
    tier: 2,
    category: "technique",
    // Batch 3a — a two-hand resting habit that keeps idle strings silent under
    // gain. A PEER of g-t2-pent-box1 (where squeal first bites), not a gate.
    // pathTags match pent-box1 (lead/expression territory, not just-play).
    prereqs: ["g-t1-palmmute", "g-t1-fretting"],
    masteryDrill: "One minute of a driven single note pentatonic line, fretting hand and picking hand quietly muting the whole time, with zero extra string noise creeping in.",
    unlock: "Can play a driven single note line with total silence around every note, no stray string noise sneaking through.",
    viz: "animation",
    chainDrillId: "g-t2-noise-control-chain",
    fluencyTest: { prompt: "Play a driven single note riff while glancing away from your hands for a few bars. No string noise sneaks in even when you are not watching your own muting hands." },
    soulTitle: "Kill the Squeal",
    keepTitle: "Noise Control Under Gain",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t2-mini-barre",
    instrument: "guitar",
    title: "Fmaj7 and the Small F",
    tier: 2,
    category: "chords",
    // Batch 3a — the two-string scaffold (Fmaj7 then the small F) before the full
    // six-string barre, the single most common quit point. Feeds g-t2-barre-E.
    // pathTags omitted = every path (just-play learners hit F just as often).
    prereqs: ["g-t1-openDGC", "g-t1-power"],
    masteryDrill: "Roll from Fmaj7 into the small F and back ten times in a row, both top strings ringing clean every time, no buzz.",
    unlock: "Can lay one finger flat across two strings for a real, song ready barre, the exact flat finger feel the full six string barre needs next.",
    viz: "chord_diagram",
    chordShape: [-1, -1, 3, 2, 1, 1],
    chainDrillId: "g-t2-mini-barre-chain",
    soulTitle: "Two Strings, First Barre",
    keepTitle: "Fmaj7 and the Small F",
  },

  // ───── Tier 3 — intermediate rewards ─────
  {
    id: "g-t3-blues12",
    instrument: "guitar",
    title: "12-Bar Blues",
    tier: 3,
    category: "repertoire",
    // #2 — gated on the G→C transition clearing fluency, so the "jam-ready"
    // unlock waits until the hard open-chord change is actually in tempo.
    prereqs: ["g-t1-power", "g-t1-strum", "g-t2-pent-box1", "g-trans-G-C"],
    masteryDrill: "12-bar in A power chords 75bpm, then solo Box1",
    unlock: "Harmonic spine of blues/rock; can jam",
    chainDrillId: "g-t3-blues12-chain",
    unlockCardId: "u-g-blues12",
    soulTitle: "The Spine of Rock",
    keepTitle: "12-Bar Blues",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t3-phrasing",
    instrument: "guitar",
    title: "Lead Phrasing — Q&A",
    tier: 3,
    category: "expression",
    prereqs: ["g-t2-pent-box1", "g-t2-vibrato"],
    masteryDrill: "4-note phrase, 1 bar silence, 4-note answer over 12-bar",
    unlock: "Solos sound musical",
    chainDrillId: "g-t3-phrasing-chain",
    unlockCardId: "u-g-phrasing",
    soulTitle: "Ask and Answer",
    keepTitle: "Lead Phrasing (Q&A)",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t3-licks",
    instrument: "guitar",
    title: "Pentatonic Licks — Box 1",
    tier: 3,
    category: "scales",
    prereqs: ["g-t2-pent-box1", "g-t2-bend", "g-t2-vibrato"],
    masteryDrill: "3 memorized licks, transposed to 2 keys each",
    unlock: "Solo with intent",
    viz: "tab",
    chainDrillId: "g-t3-licks-chain",
    soulTitle: "Musical Sentences",
    keepTitle: "Pentatonic Licks (Box 1)",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t3-fullneck",
    instrument: "guitar",
    title: "Full-Neck Pentatonic",
    tier: 3,
    category: "scales",
    prereqs: ["g-t2-pent-box2"],
    masteryDrill: "Pentatonic Highway: 5 boxes 5th→17th fret and back",
    unlock: "Full fretboard freedom",
    viz: "fretboard_map",
    chainDrillId: "g-t3-fullneck-chain",
    soulTitle: "The Whole Fretboard",
    keepTitle: "Full-Neck Pentatonic",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t3-bendaccuracy",
    instrument: "guitar",
    title: "Bending Accuracy + Expression",
    tier: 3,
    category: "technique",
    prereqs: ["g-t2-bend", "g-t2-vibrato"],
    masteryDrill: "Whole-step bends in-tune 9/10; pre-bend",
    unlock: "Real blues-rock lead",
    viz: "animation",
    soulTitle: "Feel the Pitch",
    keepTitle: "Bending Accuracy + Expression",
    pathTags: ["play-with-soul", "go-deep"],
  },
  {
    id: "g-t3-syncopation",
    instrument: "guitar",
    title: "Rhythm Syncopation & Accents",
    tier: 3,
    category: "rhythm",
    prereqs: ["g-t1-strum", "g-t1-palmmute"],
    masteryDrill: "D-x-DU-x-DU over Em 90bpm 2min, muted strokes even",
    unlock: "Rhythm sounds alive",
    chainDrillId: "g-t3-syncopation-chain",
    soulTitle: "Rhythm With Attitude",
    keepTitle: "Rhythm Syncopation & Accents",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },

  // ───── Curriculum #2 — chord-transition fluency (the song bottleneck) ─────
  // The G→C one-minute-changes drill — the notorious beginner wall behind most
  // open-chord songs. Learned when it clears ~30 clean changes/min. Depends on
  // the open D/G/C chords; gates the 12-Bar Blues as "the last reps before the
  // song" (blues is tier 3, above this — acyclic).
  {
    id: "g-trans-G-C",
    instrument: "guitar",
    title: "G → C, in time",
    tier: 2,
    category: "chords",
    prereqs: ["g-t1-openDGC"],
    masteryDrill: "One-minute changes G↔C. Count clean changes. Target 30/min.",
    unlock: "Change between G and C in tempo — the wall most beginners stall on.",
    chainDrillId: "g-trans-G-C-drill",
    soulTitle: "The Last Reps Before the Song",
    keepTitle: "G → C transition",
    pathTags: ["just-play", "play-with-soul", "go-deep"],
  },
];
